/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_AdvisorySpeedEU_H_
#define	_AdvisorySpeedEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AdvisorySpeedTypeEU.h"
#include "SpeedAdviceEU.h"
#include "SpeedConfidence.h"
#include "ZoneLengthEU.h"
#include "RestrictionClassIDEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RegionalExtensionEU;

/* AdvisorySpeedEU */
typedef struct AdvisorySpeedEU {
	AdvisorySpeedTypeEU_t	 type;
	SpeedAdviceEU_t	*speed	/* OPTIONAL */;
	SpeedConfidence_t	*confidence	/* OPTIONAL */;
	ZoneLengthEU_t	*distance	/* OPTIONAL */;
	RestrictionClassIDEU_t	*Class	/* OPTIONAL */;
	struct AdvisorySpeedEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AdvisorySpeedEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdvisorySpeedEU;
extern asn_SEQUENCE_specifics_t asn_SPC_AdvisorySpeedEU_specs_1;
extern asn_TYPE_member_t asn_MBR_AdvisorySpeedEU_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RegionalExtensionEU.h"

#endif	/* _AdvisorySpeedEU_H_ */
#include "asn_internal.h"
