/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions-NEW"
 * 	found in "../../cpm/F/kell/asd/with_riebl/CPM_NEW.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_AreaPolygon_H_
#define	_AreaPolygon_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OffsetPoint;

/* AreaPolygon */
typedef struct AreaPolygon {
	struct AreaPolygon__polyPoint {
		A_SEQUENCE_OF(struct OffsetPoint) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} polyPoint;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AreaPolygon_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AreaPolygon;
extern asn_SEQUENCE_specifics_t asn_SPC_AreaPolygon_specs_1;
extern asn_TYPE_member_t asn_MBR_AreaPolygon_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OffsetPoint.h"

#endif	/* _AreaPolygon_H_ */
#include "asn_internal.h"
