/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ConnectionManeuverAssistEU_H_
#define	_ConnectionManeuverAssistEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LaneConnectionIDEU.h"
#include "ZoneLengthEU.h"
#include "WaitOnStoplineEU.h"
#include "PedestrianBicycleDetectEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RegionalExtensionEU;

/* ConnectionManeuverAssistEU */
typedef struct ConnectionManeuverAssistEU {
	LaneConnectionIDEU_t	 connectionID;
	ZoneLengthEU_t	*queueLength	/* OPTIONAL */;
	ZoneLengthEU_t	*availableStorageLength	/* OPTIONAL */;
	WaitOnStoplineEU_t	*waitOnStop	/* OPTIONAL */;
	PedestrianBicycleDetectEU_t	*pedBicycleDetect	/* OPTIONAL */;
	struct ConnectionManeuverAssistEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConnectionManeuverAssistEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConnectionManeuverAssistEU;
extern asn_SEQUENCE_specifics_t asn_SPC_ConnectionManeuverAssistEU_specs_1;
extern asn_TYPE_member_t asn_MBR_ConnectionManeuverAssistEU_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RegionalExtensionEU.h"

#endif	/* _ConnectionManeuverAssistEU_H_ */
#include "asn_internal.h"
