/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "ConnectingLaneEU.h"

asn_TYPE_member_t asn_MBR_ConnectingLaneEU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConnectingLaneEU, lane),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneIDEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lane"
		},
	{ ATF_POINTER, 1, offsetof(struct ConnectingLaneEU, maneuver),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AllowedManeuversEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maneuver"
		},
};
static const int asn_MAP_ConnectingLaneEU_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_ConnectingLaneEU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ConnectingLaneEU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lane */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* maneuver */
};
asn_SEQUENCE_specifics_t asn_SPC_ConnectingLaneEU_specs_1 = {
	sizeof(struct ConnectingLaneEU),
	offsetof(struct ConnectingLaneEU, _asn_ctx),
	asn_MAP_ConnectingLaneEU_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_ConnectingLaneEU_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ConnectingLaneEU = {
	"ConnectingLaneEU",
	"ConnectingLaneEU",
	&asn_OP_SEQUENCE,
	asn_DEF_ConnectingLaneEU_tags_1,
	sizeof(asn_DEF_ConnectingLaneEU_tags_1)
		/sizeof(asn_DEF_ConnectingLaneEU_tags_1[0]), /* 1 */
	asn_DEF_ConnectingLaneEU_tags_1,	/* Same as above */
	sizeof(asn_DEF_ConnectingLaneEU_tags_1)
		/sizeof(asn_DEF_ConnectingLaneEU_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ConnectingLaneEU_1,
	2,	/* Elements count */
	&asn_SPC_ConnectingLaneEU_specs_1	/* Additional specs */
};

