/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_DDateTimeEU_H_
#define	_DDateTimeEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DYearEU.h"
#include "DMonthEU.h"
#include "DDayEU.h"
#include "DHourEU.h"
#include "DMinuteEU.h"
#include "DSecondEU.h"
#include "DOffsetEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DDateTimeEU */
typedef struct DDateTimeEU {
	DYearEU_t	*year	/* OPTIONAL */;
	DMonthEU_t	*month	/* OPTIONAL */;
	DDayEU_t	*day	/* OPTIONAL */;
	DHourEU_t	*hour	/* OPTIONAL */;
	DMinuteEU_t	*minute	/* OPTIONAL */;
	DSecondEU_t	*second	/* OPTIONAL */;
	DOffsetEU_t	*offset	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DDateTimeEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DDateTimeEU;
extern asn_SEQUENCE_specifics_t asn_SPC_DDateTimeEU_specs_1;
extern asn_TYPE_member_t asn_MBR_DDateTimeEU_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _DDateTimeEU_H_ */
#include "asn_internal.h"
