/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_FullPositionVectorEU_H_
#define	_FullPositionVectorEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Longitude.h"
#include "Latitude.h"
#include "ElevationEU.h"
#include "TimeConfidenceEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DDateTimeEU;
struct Heading;
struct TransmissionAndSpeedEU;
struct PositionalAccuracyEU;
struct PositionConfidenceSetEU;
struct SpeedandHeadingandThrottleConfidenceEU;

/* FullPositionVectorEU */
typedef struct FullPositionVectorEU {
	struct DDateTimeEU	*utcTime	/* OPTIONAL */;
	Longitude_t	 Long;
	Latitude_t	 lat;
	ElevationEU_t	*elevation	/* OPTIONAL */;
	struct Heading	*heading	/* OPTIONAL */;
	struct TransmissionAndSpeedEU	*speed	/* OPTIONAL */;
	struct PositionalAccuracyEU	*posAccuracy	/* OPTIONAL */;
	TimeConfidenceEU_t	*timeConfidence	/* OPTIONAL */;
	struct PositionConfidenceSetEU	*posConfidence	/* OPTIONAL */;
	struct SpeedandHeadingandThrottleConfidenceEU	*speedConfidence	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FullPositionVectorEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FullPositionVectorEU;
extern asn_SEQUENCE_specifics_t asn_SPC_FullPositionVectorEU_specs_1;
extern asn_TYPE_member_t asn_MBR_FullPositionVectorEU_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DDateTimeEU.h"
#include "Heading.h"
#include "TransmissionAndSpeedEU.h"
#include "PositionalAccuracyEU.h"
#include "PositionConfidenceSetEU.h"
#include "SpeedandHeadingandThrottleConfidenceEU.h"

#endif	/* _FullPositionVectorEU_H_ */
#include "asn_internal.h"
