/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_GNSSstatusEU_H_
#define	_GNSSstatusEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GNSSstatusEU {
	GNSSstatusEU_unavailable	= 0,
	GNSSstatusEU_isHealthy	= 1,
	GNSSstatusEU_isMonitored	= 2,
	GNSSstatusEU_baseStationType	= 3,
	GNSSstatusEU_aPDOPofUnder5	= 4,
	GNSSstatusEU_inViewOfUnder5	= 5,
	GNSSstatusEU_localCorrectionsPresent	= 6,
	GNSSstatusEU_networkCorrectionsPresent	= 7
} e_GNSSstatusEU;

/* GNSSstatusEU */
typedef BIT_STRING_t	 GNSSstatusEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_GNSSstatusEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_GNSSstatusEU;
asn_struct_free_f GNSSstatusEU_free;
asn_struct_print_f GNSSstatusEU_print;
asn_constr_check_f GNSSstatusEU_constraint;
ber_type_decoder_f GNSSstatusEU_decode_ber;
der_type_encoder_f GNSSstatusEU_encode_der;
xer_type_decoder_f GNSSstatusEU_decode_xer;
xer_type_encoder_f GNSSstatusEU_encode_xer;
oer_type_decoder_f GNSSstatusEU_decode_oer;
oer_type_encoder_f GNSSstatusEU_encode_oer;
per_type_decoder_f GNSSstatusEU_decode_uper;
per_type_encoder_f GNSSstatusEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _GNSSstatusEU_H_ */
#include "asn_internal.h"
