/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_IntersectionStateEU_H_
#define	_IntersectionStateEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DescriptiveNameEU.h"
#include "IntersectionReferenceIDEU.h"
#include "MsgCountEU.h"
#include "IntersectionStatusObjectEU.h"
#include "MinuteOfTheYearEU.h"
#include "DSecondEU.h"
#include "MovementListEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EnabledLaneListEU;
struct ManeuverAssistListEU;
struct RegionalExtensionEU;

/* IntersectionStateEU */
typedef struct IntersectionStateEU {
	DescriptiveNameEU_t	*name	/* OPTIONAL */;
	IntersectionReferenceIDEU_t	 id;
	MsgCountEU_t	 revision;
	IntersectionStatusObjectEU_t	 status;
	MinuteOfTheYearEU_t	*moy	/* OPTIONAL */;
	DSecondEU_t	*timeStamp	/* OPTIONAL */;
	struct EnabledLaneListEU	*enabledLanes	/* OPTIONAL */;
	MovementListEU_t	 states;
	struct ManeuverAssistListEU	*maneuverAssistList	/* OPTIONAL */;
	struct IntersectionStateEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersectionStateEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersectionStateEU;
extern asn_SEQUENCE_specifics_t asn_SPC_IntersectionStateEU_specs_1;
extern asn_TYPE_member_t asn_MBR_IntersectionStateEU_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EnabledLaneListEU.h"
#include "ManeuverAssistListEU.h"
#include "RegionalExtensionEU.h"

#endif	/* _IntersectionStateEU_H_ */
#include "asn_internal.h"
