/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_IntersectionAccessPointEU_H_
#define	_IntersectionAccessPointEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LaneIDEU.h"
#include "ApproachIDEU.h"
#include "LaneConnectionIDEU.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IntersectionAccessPointEU_PR {
	IntersectionAccessPointEU_PR_NOTHING,	/* No components present */
	IntersectionAccessPointEU_PR_lane,
	IntersectionAccessPointEU_PR_approach,
	IntersectionAccessPointEU_PR_connection
	/* Extensions may appear below */
	
} IntersectionAccessPointEU_PR;

/* IntersectionAccessPointEU */
typedef struct IntersectionAccessPointEU {
	IntersectionAccessPointEU_PR present;
	union IntersectionAccessPointEU_u {
		LaneIDEU_t	 lane;
		ApproachIDEU_t	 approach;
		LaneConnectionIDEU_t	 connection;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersectionAccessPointEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersectionAccessPointEU;
extern asn_CHOICE_specifics_t asn_SPC_IntersectionAccessPointEU_specs_1;
extern asn_TYPE_member_t asn_MBR_IntersectionAccessPointEU_1[3];
extern asn_per_constraints_t asn_PER_type_IntersectionAccessPointEU_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _IntersectionAccessPointEU_H_ */
#include "asn_internal.h"
