/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_IntersectionGeometryEU_H_
#define	_IntersectionGeometryEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DescriptiveNameEU.h"
#include "IntersectionReferenceIDEU.h"
#include "MsgCountEU.h"
#include "Position3DEU.h"
#include "LaneWidthEU.h"
#include "LaneListEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SpeedLimitListEU;
struct PreemptPriorityListEU;
struct RegionalExtensionEU;

/* IntersectionGeometryEU */
typedef struct IntersectionGeometryEU {
	DescriptiveNameEU_t	*name	/* OPTIONAL */;
	IntersectionReferenceIDEU_t	 id;
	MsgCountEU_t	 revision;
	Position3DEU_t	 refPoint;
	LaneWidthEU_t	*laneWidth	/* OPTIONAL */;
	struct SpeedLimitListEU	*speedLimits	/* OPTIONAL */;
	LaneListEU_t	 laneSet;
	struct PreemptPriorityListEU	*preemptPriorityData	/* OPTIONAL */;
	struct IntersectionGeometryEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersectionGeometryEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersectionGeometryEU;
extern asn_SEQUENCE_specifics_t asn_SPC_IntersectionGeometryEU_specs_1;
extern asn_TYPE_member_t asn_MBR_IntersectionGeometryEU_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SpeedLimitListEU.h"
#include "PreemptPriorityListEU.h"
#include "RegionalExtensionEU.h"

#endif	/* _IntersectionGeometryEU_H_ */
#include "asn_internal.h"
