/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ItsStationPositionEU_H_
#define	_ItsStationPositionEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "StationID.h"
#include "LaneIDEU.h"
#include "TimeReferenceEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NodeOffsetPointXYEU;

/* ItsStationPositionEU */
typedef struct ItsStationPositionEU {
	StationID_t	 stationID;
	LaneIDEU_t	*laneID	/* OPTIONAL */;
	struct NodeOffsetPointXYEU	*nodeXY	/* OPTIONAL */;
	TimeReferenceEU_t	*timeReference	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ItsStationPositionEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ItsStationPositionEU;
extern asn_SEQUENCE_specifics_t asn_SPC_ItsStationPositionEU_specs_1;
extern asn_TYPE_member_t asn_MBR_ItsStationPositionEU_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NodeOffsetPointXYEU.h"

#endif	/* _ItsStationPositionEU_H_ */
#include "asn_internal.h"
