/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_LaneAttributes_VehicleEU_H_
#define	_LaneAttributes_VehicleEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LaneAttributes_VehicleEU {
	LaneAttributes_VehicleEU_isVehicleRevocableLane	= 0,
	LaneAttributes_VehicleEU_isVehicleFlyOverLane	= 1,
	LaneAttributes_VehicleEU_hovLaneUseOnly	= 2,
	LaneAttributes_VehicleEU_restrictedToBusUse	= 3,
	LaneAttributes_VehicleEU_restrictedToTaxiUse	= 4,
	LaneAttributes_VehicleEU_restrictedFromPublicUse	= 5,
	LaneAttributes_VehicleEU_hasIRbeaconCoverage	= 6,
	LaneAttributes_VehicleEU_permissionOnRequest	= 7
} e_LaneAttributes_VehicleEU;

/* LaneAttributes-VehicleEU */
typedef BIT_STRING_t	 LaneAttributes_VehicleEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LaneAttributes_VehicleEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LaneAttributes_VehicleEU;
asn_struct_free_f LaneAttributes_VehicleEU_free;
asn_struct_print_f LaneAttributes_VehicleEU_print;
asn_constr_check_f LaneAttributes_VehicleEU_constraint;
ber_type_decoder_f LaneAttributes_VehicleEU_decode_ber;
der_type_encoder_f LaneAttributes_VehicleEU_encode_der;
xer_type_decoder_f LaneAttributes_VehicleEU_decode_xer;
xer_type_encoder_f LaneAttributes_VehicleEU_encode_xer;
oer_type_decoder_f LaneAttributes_VehicleEU_decode_oer;
oer_type_encoder_f LaneAttributes_VehicleEU_encode_oer;
per_type_decoder_f LaneAttributes_VehicleEU_decode_uper;
per_type_encoder_f LaneAttributes_VehicleEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LaneAttributes_VehicleEU_H_ */
#include "asn_internal.h"
