/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "LaneTypeAttributesEU.h"

static asn_oer_constraints_t asn_OER_type_LaneTypeAttributesEU_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_LaneTypeAttributesEU_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  7 }	/* (0..7,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_LaneTypeAttributesEU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LaneTypeAttributesEU, choice.vehicle),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneAttributes_VehicleEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"vehicle"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaneTypeAttributesEU, choice.crosswalk),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneAttributes_CrosswalkEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crosswalk"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaneTypeAttributesEU, choice.bikeLane),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneAttributes_BikeEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bikeLane"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaneTypeAttributesEU, choice.sidewalk),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneAttributes_SidewalkEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sidewalk"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaneTypeAttributesEU, choice.median),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneAttributes_BarrierEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"median"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaneTypeAttributesEU, choice.striping),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneAttributes_StripingEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"striping"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaneTypeAttributesEU, choice.trackedVehicle),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneAttributes_TrackedVehicleEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"trackedVehicle"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaneTypeAttributesEU, choice.parking),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneAttributes_ParkingEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"parking"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_LaneTypeAttributesEU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vehicle */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* crosswalk */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* bikeLane */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sidewalk */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* median */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* striping */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* trackedVehicle */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* parking */
};
asn_CHOICE_specifics_t asn_SPC_LaneTypeAttributesEU_specs_1 = {
	sizeof(struct LaneTypeAttributesEU),
	offsetof(struct LaneTypeAttributesEU, _asn_ctx),
	offsetof(struct LaneTypeAttributesEU, present),
	sizeof(((struct LaneTypeAttributesEU *)0)->present),
	asn_MAP_LaneTypeAttributesEU_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0,
	8	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_LaneTypeAttributesEU = {
	"LaneTypeAttributesEU",
	"LaneTypeAttributesEU",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_LaneTypeAttributesEU_constr_1, &asn_PER_type_LaneTypeAttributesEU_constr_1, CHOICE_constraint },
	asn_MBR_LaneTypeAttributesEU_1,
	8,	/* Elements count */
	&asn_SPC_LaneTypeAttributesEU_specs_1	/* Additional specs */
};

