/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_LaneAttributes_CrosswalkEU_H_
#define	_LaneAttributes_CrosswalkEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LaneAttributes_CrosswalkEU {
	LaneAttributes_CrosswalkEU_crosswalkRevocableLane	= 0,
	LaneAttributes_CrosswalkEU_bicyleUseAllowed	= 1,
	LaneAttributes_CrosswalkEU_isXwalkFlyOverLane	= 2,
	LaneAttributes_CrosswalkEU_fixedCycleTime	= 3,
	LaneAttributes_CrosswalkEU_biDirectionalCycleTimes	= 4,
	LaneAttributes_CrosswalkEU_hasPushToWalkButton	= 5,
	LaneAttributes_CrosswalkEU_audioSupport	= 6,
	LaneAttributes_CrosswalkEU_rfSignalRequestPresent	= 7,
	LaneAttributes_CrosswalkEU_unsignalizedSegmentsPresent	= 8
} e_LaneAttributes_CrosswalkEU;

/* LaneAttributes-CrosswalkEU */
typedef BIT_STRING_t	 LaneAttributes_CrosswalkEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LaneAttributes_CrosswalkEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LaneAttributes_CrosswalkEU;
asn_struct_free_f LaneAttributes_CrosswalkEU_free;
asn_struct_print_f LaneAttributes_CrosswalkEU_print;
asn_constr_check_f LaneAttributes_CrosswalkEU_constraint;
ber_type_decoder_f LaneAttributes_CrosswalkEU_decode_ber;
der_type_encoder_f LaneAttributes_CrosswalkEU_encode_der;
xer_type_decoder_f LaneAttributes_CrosswalkEU_decode_xer;
xer_type_encoder_f LaneAttributes_CrosswalkEU_encode_xer;
oer_type_decoder_f LaneAttributes_CrosswalkEU_decode_oer;
oer_type_encoder_f LaneAttributes_CrosswalkEU_encode_oer;
per_type_decoder_f LaneAttributes_CrosswalkEU_decode_uper;
per_type_encoder_f LaneAttributes_CrosswalkEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LaneAttributes_CrosswalkEU_H_ */
#include "asn_internal.h"
