/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_LaneAttributesEU_addGrpCEU_H_
#define	_LaneAttributesEU_addGrpCEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VehicleHeightEU.h"
#include "VehicleMassEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LaneAttributesEU-addGrpCEU */
typedef struct LaneAttributesEU_addGrpCEU {
	VehicleHeightEU_t	*maxVehicleHeight	/* OPTIONAL */;
	VehicleMassEU_t	*maxVehicleWeight	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LaneAttributesEU_addGrpCEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaneAttributesEU_addGrpCEU;

#ifdef __cplusplus
}
#endif

#endif	/* _LaneAttributesEU_addGrpCEU_H_ */
#include "asn_internal.h"
