/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_LaneConnectionIDEU_H_
#define	_LaneConnectionIDEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LaneConnectionIDEU */
typedef long	 LaneConnectionIDEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LaneConnectionIDEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LaneConnectionIDEU;
asn_struct_free_f LaneConnectionIDEU_free;
asn_struct_print_f LaneConnectionIDEU_print;
asn_constr_check_f LaneConnectionIDEU_constraint;
ber_type_decoder_f LaneConnectionIDEU_decode_ber;
der_type_encoder_f LaneConnectionIDEU_encode_der;
xer_type_decoder_f LaneConnectionIDEU_decode_xer;
xer_type_encoder_f LaneConnectionIDEU_encode_xer;
oer_type_decoder_f LaneConnectionIDEU_decode_oer;
oer_type_encoder_f LaneConnectionIDEU_encode_oer;
per_type_decoder_f LaneConnectionIDEU_decode_uper;
per_type_encoder_f LaneConnectionIDEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LaneConnectionIDEU_H_ */
#include "asn_internal.h"
