/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_MapDataEU_H_
#define	_MapDataEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MinuteOfTheYearEU.h"
#include "MsgCountEU.h"
#include "LayerTypeEU.h"
#include "LayerIDEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IntersectionGeometryListEU;
struct RoadSegmentListEU;
struct DataParametersEU;
struct RestrictionClassListEU;
struct RegionalExtensionEU;

/* MapDataEU */
typedef struct MapDataEU {
	MinuteOfTheYearEU_t	*timeStamp	/* OPTIONAL */;
	MsgCountEU_t	 msgIssueRevision;
	LayerTypeEU_t	*layerType	/* OPTIONAL */;
	LayerIDEU_t	*layerID	/* OPTIONAL */;
	struct IntersectionGeometryListEU	*intersections	/* OPTIONAL */;
	struct RoadSegmentListEU	*roadSegments	/* OPTIONAL */;
	struct DataParametersEU	*dataParameters	/* OPTIONAL */;
	struct RestrictionClassListEU	*restrictionList	/* OPTIONAL */;
	struct MapDataEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MapDataEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MapDataEU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IntersectionGeometryListEU.h"
#include "RoadSegmentListEU.h"
#include "DataParametersEU.h"
#include "RestrictionClassListEU.h"
#include "RegionalExtensionEU.h"

#endif	/* _MapDataEU_H_ */
#include "asn_internal.h"
