/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_MovementStateEU_H_
#define	_MovementStateEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DescriptiveNameEU.h"
#include "SignalGroupIDEU.h"
#include "MovementEventListEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ManeuverAssistListEU;
struct RegionalExtensionEU;

/* MovementStateEU */
typedef struct MovementStateEU {
	DescriptiveNameEU_t	*movementName	/* OPTIONAL */;
	SignalGroupIDEU_t	 signalGroup;
	MovementEventListEU_t	 state_time_speed;
	struct ManeuverAssistListEU	*maneuverAssistList	/* OPTIONAL */;
	struct MovementStateEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MovementStateEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MovementStateEU;
extern asn_SEQUENCE_specifics_t asn_SPC_MovementStateEU_specs_1;
extern asn_TYPE_member_t asn_MBR_MovementStateEU_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ManeuverAssistListEU.h"
#include "RegionalExtensionEU.h"

#endif	/* _MovementStateEU_H_ */
#include "asn_internal.h"
