/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_NodeAttributeXYEU_H_
#define	_NodeAttributeXYEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NodeAttributeXYEU {
	NodeAttributeXYEU_reserved	= 0,
	NodeAttributeXYEU_stopLine	= 1,
	NodeAttributeXYEU_roundedCapStyleA	= 2,
	NodeAttributeXYEU_roundedCapStyleB	= 3,
	NodeAttributeXYEU_mergePoint	= 4,
	NodeAttributeXYEU_divergePoint	= 5,
	NodeAttributeXYEU_downstreamStopLine	= 6,
	NodeAttributeXYEU_downstreamStartNode	= 7,
	NodeAttributeXYEU_closedToTraffic	= 8,
	NodeAttributeXYEU_safeIsland	= 9,
	NodeAttributeXYEU_curbPresentAtStepOff	= 10,
	NodeAttributeXYEU_hydrantPresent	= 11
	/*
	 * Enumeration is extensible
	 */
} e_NodeAttributeXYEU;

/* NodeAttributeXYEU */
typedef long	 NodeAttributeXYEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NodeAttributeXYEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NodeAttributeXYEU;
extern const asn_INTEGER_specifics_t asn_SPC_NodeAttributeXYEU_specs_1;
asn_struct_free_f NodeAttributeXYEU_free;
asn_struct_print_f NodeAttributeXYEU_print;
asn_constr_check_f NodeAttributeXYEU_constraint;
ber_type_decoder_f NodeAttributeXYEU_decode_ber;
der_type_encoder_f NodeAttributeXYEU_encode_der;
xer_type_decoder_f NodeAttributeXYEU_decode_xer;
xer_type_encoder_f NodeAttributeXYEU_encode_xer;
oer_type_decoder_f NodeAttributeXYEU_decode_oer;
oer_type_encoder_f NodeAttributeXYEU_encode_oer;
per_type_decoder_f NodeAttributeXYEU_decode_uper;
per_type_encoder_f NodeAttributeXYEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NodeAttributeXYEU_H_ */
#include "asn_internal.h"
