/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_NodeListXYEU_H_
#define	_NodeListXYEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NodeSetXYEU.h"
#include "ComputedLaneEU.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NodeListXYEU_PR {
	NodeListXYEU_PR_NOTHING,	/* No components present */
	NodeListXYEU_PR_nodes,
	NodeListXYEU_PR_computed
	/* Extensions may appear below */
	
} NodeListXYEU_PR;

/* NodeListXYEU */
typedef struct NodeListXYEU {
	NodeListXYEU_PR present;
	union NodeListXYEU_u {
		NodeSetXYEU_t	 nodes;
		ComputedLaneEU_t	 computed;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NodeListXYEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeListXYEU;
extern asn_CHOICE_specifics_t asn_SPC_NodeListXYEU_specs_1;
extern asn_TYPE_member_t asn_MBR_NodeListXYEU_1[2];
extern asn_per_constraints_t asn_PER_type_NodeListXYEU_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NodeListXYEU_H_ */
#include "asn_internal.h"
