/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_Node_XY_26bEU_H_
#define	_Node_XY_26bEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Offset-B13EU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Node-XY-26bEU */
typedef struct Node_XY_26bEU {
	Offset_B13EU_t	 x;
	Offset_B13EU_t	 y;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Node_XY_26bEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Node_XY_26bEU;
extern asn_SEQUENCE_specifics_t asn_SPC_Node_XY_26bEU_specs_1;
extern asn_TYPE_member_t asn_MBR_Node_XY_26bEU_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Node_XY_26bEU_H_ */
#include "asn_internal.h"
