/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions-NEW"
 * 	found in "../../cpm/F/kell/asd/with_riebl/CPM_NEW.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_OffsetPoint_H_
#define	_OffsetPoint_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NodeOffsetPointXYEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NodeOffsetPointZ;

/* OffsetPoint */
typedef struct OffsetPoint {
	NodeOffsetPointXYEU_t	 nodeOffsetPointxy;
	struct NodeOffsetPointZ	*nodeOffsetPointZ	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OffsetPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OffsetPoint;
extern asn_SEQUENCE_specifics_t asn_SPC_OffsetPoint_specs_1;
extern asn_TYPE_member_t asn_MBR_OffsetPoint_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NodeOffsetPointZ.h"

#endif	/* _OffsetPoint_H_ */
#include "asn_internal.h"
