/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PositionConfidenceSetEU_H_
#define	_PositionConfidenceSetEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PositionConfidenceEU.h"
#include "ElevationConfidenceEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PositionConfidenceSetEU */
typedef struct PositionConfidenceSetEU {
	PositionConfidenceEU_t	 pos;
	ElevationConfidenceEU_t	 elevation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PositionConfidenceSetEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionConfidenceSetEU;
extern asn_SEQUENCE_specifics_t asn_SPC_PositionConfidenceSetEU_specs_1;
extern asn_TYPE_member_t asn_MBR_PositionConfidenceSetEU_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PositionConfidenceSetEU_H_ */
#include "asn_internal.h"
