/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PositionConfidenceEU_H_
#define	_PositionConfidenceEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PositionConfidenceEU {
	PositionConfidenceEU_unavailable	= 0,
	PositionConfidenceEU_a500m	= 1,
	PositionConfidenceEU_a200m	= 2,
	PositionConfidenceEU_a100m	= 3,
	PositionConfidenceEU_a50m	= 4,
	PositionConfidenceEU_a20m	= 5,
	PositionConfidenceEU_a10m	= 6,
	PositionConfidenceEU_a5m	= 7,
	PositionConfidenceEU_a2m	= 8,
	PositionConfidenceEU_a1m	= 9,
	PositionConfidenceEU_a50cm	= 10,
	PositionConfidenceEU_a20cm	= 11,
	PositionConfidenceEU_a10cm	= 12,
	PositionConfidenceEU_a5cm	= 13,
	PositionConfidenceEU_a2cm	= 14,
	PositionConfidenceEU_a1cm	= 15
} e_PositionConfidenceEU;

/* PositionConfidenceEU */
typedef long	 PositionConfidenceEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PositionConfidenceEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PositionConfidenceEU;
extern const asn_INTEGER_specifics_t asn_SPC_PositionConfidenceEU_specs_1;
asn_struct_free_f PositionConfidenceEU_free;
asn_struct_print_f PositionConfidenceEU_print;
asn_constr_check_f PositionConfidenceEU_constraint;
ber_type_decoder_f PositionConfidenceEU_decode_ber;
der_type_encoder_f PositionConfidenceEU_encode_der;
xer_type_decoder_f PositionConfidenceEU_decode_xer;
xer_type_encoder_f PositionConfidenceEU_encode_xer;
oer_type_decoder_f PositionConfidenceEU_decode_oer;
oer_type_encoder_f PositionConfidenceEU_encode_oer;
per_type_decoder_f PositionConfidenceEU_decode_uper;
per_type_encoder_f PositionConfidenceEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PositionConfidenceEU_H_ */
#include "asn_internal.h"
