/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PtvRequestTypeEU_H_
#define	_PtvRequestTypeEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PtvRequestTypeEU {
	PtvRequestTypeEU_preRequest	= 0,
	PtvRequestTypeEU_mainRequest	= 1,
	PtvRequestTypeEU_doorCloseRequest	= 2,
	PtvRequestTypeEU_cancelRequest	= 3,
	PtvRequestTypeEU_emergencyRequest	= 4
	/*
	 * Enumeration is extensible
	 */
} e_PtvRequestTypeEU;

/* PtvRequestTypeEU */
typedef long	 PtvRequestTypeEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PtvRequestTypeEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PtvRequestTypeEU;
extern const asn_INTEGER_specifics_t asn_SPC_PtvRequestTypeEU_specs_1;
asn_struct_free_f PtvRequestTypeEU_free;
asn_struct_print_f PtvRequestTypeEU_print;
asn_constr_check_f PtvRequestTypeEU_constraint;
ber_type_decoder_f PtvRequestTypeEU_decode_ber;
der_type_encoder_f PtvRequestTypeEU_encode_der;
xer_type_decoder_f PtvRequestTypeEU_decode_xer;
xer_type_encoder_f PtvRequestTypeEU_encode_xer;
oer_type_decoder_f PtvRequestTypeEU_decode_oer;
oer_type_encoder_f PtvRequestTypeEU_encode_oer;
per_type_decoder_f PtvRequestTypeEU_decode_uper;
per_type_encoder_f PtvRequestTypeEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PtvRequestTypeEU_H_ */
#include "asn_internal.h"
