/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RequestorDescriptionEU_H_
#define	_RequestorDescriptionEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VehicleIDEU.h"
#include "DescriptiveNameEU.h"
#include "TransitVehicleStatusEU.h"
#include "TransitVehicleOccupancyEU.h"
#include "DeltaTimeEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RequestorTypeEU;
struct RequestorPositionVectorEU;
struct RegionalExtensionEU;

/* RequestorDescriptionEU */
typedef struct RequestorDescriptionEU {
	VehicleIDEU_t	 id;
	struct RequestorTypeEU	*type	/* OPTIONAL */;
	struct RequestorPositionVectorEU	*position	/* OPTIONAL */;
	DescriptiveNameEU_t	*name	/* OPTIONAL */;
	DescriptiveNameEU_t	*routeName	/* OPTIONAL */;
	TransitVehicleStatusEU_t	*transitStatus	/* OPTIONAL */;
	TransitVehicleOccupancyEU_t	*transitOccupancy	/* OPTIONAL */;
	DeltaTimeEU_t	*transitSchedule	/* OPTIONAL */;
	struct RequestorDescriptionEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RequestorDescriptionEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RequestorDescriptionEU;
extern asn_SEQUENCE_specifics_t asn_SPC_RequestorDescriptionEU_specs_1;
extern asn_TYPE_member_t asn_MBR_RequestorDescriptionEU_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RequestorTypeEU.h"
#include "RequestorPositionVectorEU.h"
#include "RegionalExtensionEU.h"

#endif	/* _RequestorDescriptionEU_H_ */
#include "asn_internal.h"
