/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RestrictionUserTypeEU_H_
#define	_RestrictionUserTypeEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RestrictionAppliesToEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RestrictionUserTypeEU_PR {
	RestrictionUserTypeEU_PR_NOTHING,	/* No components present */
	RestrictionUserTypeEU_PR_basicType,
	RestrictionUserTypeEU_PR_regional
	/* Extensions may appear below */
	
} RestrictionUserTypeEU_PR;

/* Forward declarations */
struct RegionalExtensionEU;

/* RestrictionUserTypeEU */
typedef struct RestrictionUserTypeEU {
	RestrictionUserTypeEU_PR present;
	union RestrictionUserTypeEU_u {
		RestrictionAppliesToEU_t	 basicType;
		struct RestrictionUserTypeEU__regional {
			A_SEQUENCE_OF(struct RegionalExtensionEU) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} regional;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RestrictionUserTypeEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RestrictionUserTypeEU;
extern asn_CHOICE_specifics_t asn_SPC_RestrictionUserTypeEU_specs_1;
extern asn_TYPE_member_t asn_MBR_RestrictionUserTypeEU_1[2];
extern asn_per_constraints_t asn_PER_type_RestrictionUserTypeEU_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RegionalExtensionEU.h"

#endif	/* _RestrictionUserTypeEU_H_ */
#include "asn_internal.h"
