/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RestrictionAppliesToEU_H_
#define	_RestrictionAppliesToEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RestrictionAppliesToEU {
	RestrictionAppliesToEU_none	= 0,
	RestrictionAppliesToEU_equippedTransit	= 1,
	RestrictionAppliesToEU_equippedTaxis	= 2,
	RestrictionAppliesToEU_equippedOther	= 3,
	RestrictionAppliesToEU_emissionCompliant	= 4,
	RestrictionAppliesToEU_equippedBicycle	= 5,
	RestrictionAppliesToEU_weightCompliant	= 6,
	RestrictionAppliesToEU_heightCompliant	= 7,
	RestrictionAppliesToEU_pedestrians	= 8,
	RestrictionAppliesToEU_slowMovingPersons	= 9,
	RestrictionAppliesToEU_wheelchairUsers	= 10,
	RestrictionAppliesToEU_visualDisabilities	= 11,
	RestrictionAppliesToEU_audioDisabilities	= 12,
	RestrictionAppliesToEU_otherUnknownDisabilities	= 13
	/*
	 * Enumeration is extensible
	 */
} e_RestrictionAppliesToEU;

/* RestrictionAppliesToEU */
typedef long	 RestrictionAppliesToEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RestrictionAppliesToEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RestrictionAppliesToEU;
extern const asn_INTEGER_specifics_t asn_SPC_RestrictionAppliesToEU_specs_1;
asn_struct_free_f RestrictionAppliesToEU_free;
asn_struct_print_f RestrictionAppliesToEU_print;
asn_constr_check_f RestrictionAppliesToEU_constraint;
ber_type_decoder_f RestrictionAppliesToEU_decode_ber;
der_type_encoder_f RestrictionAppliesToEU_encode_der;
xer_type_decoder_f RestrictionAppliesToEU_decode_xer;
xer_type_encoder_f RestrictionAppliesToEU_encode_xer;
oer_type_decoder_f RestrictionAppliesToEU_decode_oer;
oer_type_encoder_f RestrictionAppliesToEU_encode_oer;
per_type_decoder_f RestrictionAppliesToEU_decode_uper;
per_type_encoder_f RestrictionAppliesToEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RestrictionAppliesToEU_H_ */
#include "asn_internal.h"
