/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RoadSegmentEU_H_
#define	_RoadSegmentEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DescriptiveNameEU.h"
#include "RoadSegmentReferenceIDEU.h"
#include "MsgCountEU.h"
#include "Position3DEU.h"
#include "LaneWidthEU.h"
#include "RoadLaneSetListEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SpeedLimitListEU;
struct RegionalExtensionEU;

/* RoadSegmentEU */
typedef struct RoadSegmentEU {
	DescriptiveNameEU_t	*name	/* OPTIONAL */;
	RoadSegmentReferenceIDEU_t	 id;
	MsgCountEU_t	 revision;
	Position3DEU_t	 refPoint;
	LaneWidthEU_t	*laneWidth	/* OPTIONAL */;
	struct SpeedLimitListEU	*speedLimits	/* OPTIONAL */;
	RoadLaneSetListEU_t	 roadLaneSet;
	struct RoadSegmentEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadSegmentEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadSegmentEU;
extern asn_SEQUENCE_specifics_t asn_SPC_RoadSegmentEU_specs_1;
extern asn_TYPE_member_t asn_MBR_RoadSegmentEU_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SpeedLimitListEU.h"
#include "RegionalExtensionEU.h"

#endif	/* _RoadSegmentEU_H_ */
#include "asn_internal.h"
