/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RoadSegmentListEU_H_
#define	_RoadSegmentListEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RoadSegmentEU;

/* RoadSegmentListEU */
typedef struct RoadSegmentListEU {
	A_SEQUENCE_OF(struct RoadSegmentEU) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadSegmentListEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadSegmentListEU;
extern asn_SET_OF_specifics_t asn_SPC_RoadSegmentListEU_specs_1;
extern asn_TYPE_member_t asn_MBR_RoadSegmentListEU_1[1];
extern asn_per_constraints_t asn_PER_type_RoadSegmentListEU_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RoadSegmentEU.h"

#endif	/* _RoadSegmentListEU_H_ */
#include "asn_internal.h"
