/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RTCMmessageListEU_H_
#define	_RTCMmessageListEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RTCMmessageEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RTCMmessageListEU */
typedef struct RTCMmessageListEU {
	A_SEQUENCE_OF(RTCMmessageEU_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RTCMmessageListEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RTCMmessageListEU;
extern asn_SET_OF_specifics_t asn_SPC_RTCMmessageListEU_specs_1;
extern asn_TYPE_member_t asn_MBR_RTCMmessageListEU_1[1];
extern asn_per_constraints_t asn_PER_type_RTCMmessageListEU_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RTCMmessageListEU_H_ */
#include "asn_internal.h"
