/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RTCM_RevisionEU_H_
#define	_RTCM_RevisionEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RTCM_RevisionEU {
	RTCM_RevisionEU_unknown	= 0,
	RTCM_RevisionEU_rtcmRev2	= 1,
	RTCM_RevisionEU_rtcmRev3	= 2,
	RTCM_RevisionEU_reserved	= 3
	/*
	 * Enumeration is extensible
	 */
} e_RTCM_RevisionEU;

/* RTCM-RevisionEU */
typedef long	 RTCM_RevisionEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RTCM_RevisionEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RTCM_RevisionEU;
extern const asn_INTEGER_specifics_t asn_SPC_RTCM_RevisionEU_specs_1;
asn_struct_free_f RTCM_RevisionEU_free;
asn_struct_print_f RTCM_RevisionEU_print;
asn_constr_check_f RTCM_RevisionEU_constraint;
ber_type_decoder_f RTCM_RevisionEU_decode_ber;
der_type_encoder_f RTCM_RevisionEU_encode_der;
xer_type_decoder_f RTCM_RevisionEU_decode_xer;
xer_type_encoder_f RTCM_RevisionEU_encode_xer;
oer_type_decoder_f RTCM_RevisionEU_decode_oer;
oer_type_encoder_f RTCM_RevisionEU_encode_oer;
per_type_decoder_f RTCM_RevisionEU_decode_uper;
per_type_encoder_f RTCM_RevisionEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RTCM_RevisionEU_H_ */
#include "asn_internal.h"
