/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SegmentAttributeXYEU_H_
#define	_SegmentAttributeXYEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SegmentAttributeXYEU {
	SegmentAttributeXYEU_reserved	= 0,
	SegmentAttributeXYEU_doNotBlock	= 1,
	SegmentAttributeXYEU_whiteLine	= 2,
	SegmentAttributeXYEU_mergingLaneLeft	= 3,
	SegmentAttributeXYEU_mergingLaneRight	= 4,
	SegmentAttributeXYEU_curbOnLeft	= 5,
	SegmentAttributeXYEU_curbOnRight	= 6,
	SegmentAttributeXYEU_loadingzoneOnLeft	= 7,
	SegmentAttributeXYEU_loadingzoneOnRight	= 8,
	SegmentAttributeXYEU_turnOutPointOnLeft	= 9,
	SegmentAttributeXYEU_turnOutPointOnRight	= 10,
	SegmentAttributeXYEU_adjacentParkingOnLeft	= 11,
	SegmentAttributeXYEU_adjacentParkingOnRight	= 12,
	SegmentAttributeXYEU_adjacentBikeLaneOnLeft	= 13,
	SegmentAttributeXYEU_adjacentBikeLaneOnRight	= 14,
	SegmentAttributeXYEU_sharedBikeLane	= 15,
	SegmentAttributeXYEU_bikeBoxInFront	= 16,
	SegmentAttributeXYEU_transitStopOnLeft	= 17,
	SegmentAttributeXYEU_transitStopOnRight	= 18,
	SegmentAttributeXYEU_transitStopInLane	= 19,
	SegmentAttributeXYEU_sharedWithTrackedVehicle	= 20,
	SegmentAttributeXYEU_safeIsland	= 21,
	SegmentAttributeXYEU_lowCurbsPresent	= 22,
	SegmentAttributeXYEU_rumbleStripPresent	= 23,
	SegmentAttributeXYEU_audibleSignalingPresent	= 24,
	SegmentAttributeXYEU_adaptiveTimingPresent	= 25,
	SegmentAttributeXYEU_rfSignalRequestPresent	= 26,
	SegmentAttributeXYEU_partialCurbIntrusion	= 27,
	SegmentAttributeXYEU_taperToLeft	= 28,
	SegmentAttributeXYEU_taperToRight	= 29,
	SegmentAttributeXYEU_taperToCenterLine	= 30,
	SegmentAttributeXYEU_parallelParking	= 31,
	SegmentAttributeXYEU_headInParking	= 32,
	SegmentAttributeXYEU_freeParking	= 33,
	SegmentAttributeXYEU_timeRestrictionsOnParking	= 34,
	SegmentAttributeXYEU_costToPark	= 35,
	SegmentAttributeXYEU_midBlockCurbPresent	= 36,
	SegmentAttributeXYEU_unEvenPavementPresent	= 37
	/*
	 * Enumeration is extensible
	 */
} e_SegmentAttributeXYEU;

/* SegmentAttributeXYEU */
typedef long	 SegmentAttributeXYEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SegmentAttributeXYEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SegmentAttributeXYEU;
extern const asn_INTEGER_specifics_t asn_SPC_SegmentAttributeXYEU_specs_1;
asn_struct_free_f SegmentAttributeXYEU_free;
asn_struct_print_f SegmentAttributeXYEU_print;
asn_constr_check_f SegmentAttributeXYEU_constraint;
ber_type_decoder_f SegmentAttributeXYEU_decode_ber;
der_type_encoder_f SegmentAttributeXYEU_encode_der;
xer_type_decoder_f SegmentAttributeXYEU_decode_xer;
xer_type_encoder_f SegmentAttributeXYEU_encode_xer;
oer_type_decoder_f SegmentAttributeXYEU_decode_oer;
oer_type_encoder_f SegmentAttributeXYEU_encode_oer;
per_type_decoder_f SegmentAttributeXYEU_decode_uper;
per_type_encoder_f SegmentAttributeXYEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SegmentAttributeXYEU_H_ */
#include "asn_internal.h"
