/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions-NEW"
 * 	found in "../../cpm/F/kell/asd/with_riebl/CPM_NEW.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SensorInformation_H_
#define	_SensorInformation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier.h"
#include "SensorType.h"
#include "BOOLEAN.h"
#include "DetectionArea.h"
#include "FreeSpaceConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SensorInformation */
typedef struct SensorInformation {
	Identifier_t	 id;
	SensorType_t	 type;
	BOOLEAN_t	*occupied	/* OPTIONAL */;
	DetectionArea_t	 detectionArea;
	FreeSpaceConfidence_t	*freeSpaceConfidence	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SensorInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SensorInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_SensorInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_SensorInformation_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _SensorInformation_H_ */
#include "asn_internal.h"
