/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "SignalHeadLocationEU.h"

asn_TYPE_member_t asn_MBR_SignalHeadLocationEU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SignalHeadLocationEU, nodeXY),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NodeOffsetPointXYEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nodeXY"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignalHeadLocationEU, nodeZ),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DeltaAltitude,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nodeZ"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignalHeadLocationEU, signalGroupID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SignalGroupIDEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signalGroupID"
		},
};
static const ber_tlv_tag_t asn_DEF_SignalHeadLocationEU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SignalHeadLocationEU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nodeXY */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* nodeZ */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* signalGroupID */
};
asn_SEQUENCE_specifics_t asn_SPC_SignalHeadLocationEU_specs_1 = {
	sizeof(struct SignalHeadLocationEU),
	offsetof(struct SignalHeadLocationEU, _asn_ctx),
	asn_MAP_SignalHeadLocationEU_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SignalHeadLocationEU = {
	"SignalHeadLocationEU",
	"SignalHeadLocationEU",
	&asn_OP_SEQUENCE,
	asn_DEF_SignalHeadLocationEU_tags_1,
	sizeof(asn_DEF_SignalHeadLocationEU_tags_1)
		/sizeof(asn_DEF_SignalHeadLocationEU_tags_1[0]), /* 1 */
	asn_DEF_SignalHeadLocationEU_tags_1,	/* Same as above */
	sizeof(asn_DEF_SignalHeadLocationEU_tags_1)
		/sizeof(asn_DEF_SignalHeadLocationEU_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SignalHeadLocationEU_1,
	3,	/* Elements count */
	&asn_SPC_SignalHeadLocationEU_specs_1	/* Additional specs */
};

