/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "SignalRequesterInfoEU.h"

asn_TYPE_member_t asn_MBR_SignalRequesterInfoEU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SignalRequesterInfoEU, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_VehicleIDEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignalRequesterInfoEU, request),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RequestIDEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignalRequesterInfoEU, sequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgCountEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sequenceNumber"
		},
	{ ATF_POINTER, 2, offsetof(struct SignalRequesterInfoEU, role),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BasicVehicleRoleEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"role"
		},
	{ ATF_POINTER, 1, offsetof(struct SignalRequesterInfoEU, typeData),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RequestorTypeEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"typeData"
		},
};
static const int asn_MAP_SignalRequesterInfoEU_oms_1[] = { 3, 4 };
static const ber_tlv_tag_t asn_DEF_SignalRequesterInfoEU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SignalRequesterInfoEU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* request */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sequenceNumber */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* role */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* typeData */
};
asn_SEQUENCE_specifics_t asn_SPC_SignalRequesterInfoEU_specs_1 = {
	sizeof(struct SignalRequesterInfoEU),
	offsetof(struct SignalRequesterInfoEU, _asn_ctx),
	asn_MAP_SignalRequesterInfoEU_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_SignalRequesterInfoEU_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SignalRequesterInfoEU = {
	"SignalRequesterInfoEU",
	"SignalRequesterInfoEU",
	&asn_OP_SEQUENCE,
	asn_DEF_SignalRequesterInfoEU_tags_1,
	sizeof(asn_DEF_SignalRequesterInfoEU_tags_1)
		/sizeof(asn_DEF_SignalRequesterInfoEU_tags_1[0]), /* 1 */
	asn_DEF_SignalRequesterInfoEU_tags_1,	/* Same as above */
	sizeof(asn_DEF_SignalRequesterInfoEU_tags_1)
		/sizeof(asn_DEF_SignalRequesterInfoEU_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SignalRequesterInfoEU_1,
	5,	/* Elements count */
	&asn_SPC_SignalRequesterInfoEU_specs_1	/* Additional specs */
};

