/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SignalRequestPackageEU_H_
#define	_SignalRequestPackageEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SignalRequestEU.h"
#include "MinuteOfTheYearEU.h"
#include "DSecondEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RegionalExtensionEU;

/* SignalRequestPackageEU */
typedef struct SignalRequestPackageEU {
	SignalRequestEU_t	 request;
	MinuteOfTheYearEU_t	*minute	/* OPTIONAL */;
	DSecondEU_t	*second	/* OPTIONAL */;
	DSecondEU_t	*duration	/* OPTIONAL */;
	struct SignalRequestPackageEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalRequestPackageEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalRequestPackageEU;
extern asn_SEQUENCE_specifics_t asn_SPC_SignalRequestPackageEU_specs_1;
extern asn_TYPE_member_t asn_MBR_SignalRequestPackageEU_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RegionalExtensionEU.h"

#endif	/* _SignalRequestPackageEU_H_ */
#include "asn_internal.h"
