/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_TimeReferenceEU_H_
#define	_TimeReferenceEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TimeReferenceEU {
	TimeReferenceEU_oneMilliSec	= 1
} e_TimeReferenceEU;

/* TimeReferenceEU */
typedef long	 TimeReferenceEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TimeReferenceEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TimeReferenceEU;
asn_struct_free_f TimeReferenceEU_free;
asn_struct_print_f TimeReferenceEU_print;
asn_constr_check_f TimeReferenceEU_constraint;
ber_type_decoder_f TimeReferenceEU_decode_ber;
der_type_encoder_f TimeReferenceEU_encode_der;
xer_type_decoder_f TimeReferenceEU_decode_xer;
xer_type_encoder_f TimeReferenceEU_encode_xer;
oer_type_decoder_f TimeReferenceEU_decode_oer;
oer_type_encoder_f TimeReferenceEU_encode_oer;
per_type_decoder_f TimeReferenceEU_decode_uper;
per_type_encoder_f TimeReferenceEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeReferenceEU_H_ */
#include "asn_internal.h"
