/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_TransmissionAndSpeedEU_H_
#define	_TransmissionAndSpeedEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TransmissionStateEU.h"
#include "VelocityEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TransmissionAndSpeedEU */
typedef struct TransmissionAndSpeedEU {
	TransmissionStateEU_t	 transmisson;
	VelocityEU_t	 speed;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TransmissionAndSpeedEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransmissionAndSpeedEU;
extern asn_SEQUENCE_specifics_t asn_SPC_TransmissionAndSpeedEU_specs_1;
extern asn_TYPE_member_t asn_MBR_TransmissionAndSpeedEU_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TransmissionAndSpeedEU_H_ */
#include "asn_internal.h"
