/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_TransitVehicleOccupancyEU_H_
#define	_TransitVehicleOccupancyEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TransitVehicleOccupancyEU {
	TransitVehicleOccupancyEU_occupancyUnknown	= 0,
	TransitVehicleOccupancyEU_occupancyEmpty	= 1,
	TransitVehicleOccupancyEU_occupancyVeryLow	= 2,
	TransitVehicleOccupancyEU_occupancyLow	= 3,
	TransitVehicleOccupancyEU_occupancyMed	= 4,
	TransitVehicleOccupancyEU_occupancyHigh	= 5,
	TransitVehicleOccupancyEU_occupancyNearlyFull	= 6,
	TransitVehicleOccupancyEU_occupancyFull	= 7
} e_TransitVehicleOccupancyEU;

/* TransitVehicleOccupancyEU */
typedef long	 TransitVehicleOccupancyEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TransitVehicleOccupancyEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TransitVehicleOccupancyEU;
extern const asn_INTEGER_specifics_t asn_SPC_TransitVehicleOccupancyEU_specs_1;
asn_struct_free_f TransitVehicleOccupancyEU_free;
asn_struct_print_f TransitVehicleOccupancyEU_print;
asn_constr_check_f TransitVehicleOccupancyEU_constraint;
ber_type_decoder_f TransitVehicleOccupancyEU_decode_ber;
der_type_encoder_f TransitVehicleOccupancyEU_encode_der;
xer_type_decoder_f TransitVehicleOccupancyEU_decode_xer;
xer_type_encoder_f TransitVehicleOccupancyEU_encode_xer;
oer_type_decoder_f TransitVehicleOccupancyEU_decode_oer;
oer_type_encoder_f TransitVehicleOccupancyEU_encode_oer;
per_type_decoder_f TransitVehicleOccupancyEU_decode_uper;
per_type_encoder_f TransitVehicleOccupancyEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TransitVehicleOccupancyEU_H_ */
#include "asn_internal.h"
