/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_VehicleTypeEU_H_
#define	_VehicleTypeEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleTypeEU {
	VehicleTypeEU_none	= 0,
	VehicleTypeEU_unknown	= 1,
	VehicleTypeEU_special	= 2,
	VehicleTypeEU_moto	= 3,
	VehicleTypeEU_car	= 4,
	VehicleTypeEU_carOther	= 5,
	VehicleTypeEU_bus	= 6,
	VehicleTypeEU_axleCnt2	= 7,
	VehicleTypeEU_axleCnt3	= 8,
	VehicleTypeEU_axleCnt4	= 9,
	VehicleTypeEU_axleCnt4Trailer	= 10,
	VehicleTypeEU_axleCnt5Trailer	= 11,
	VehicleTypeEU_axleCnt6Trailer	= 12,
	VehicleTypeEU_axleCnt5MultiTrailer	= 13,
	VehicleTypeEU_axleCnt6MultiTrailer	= 14,
	VehicleTypeEU_axleCnt7MultiTrailer	= 15
	/*
	 * Enumeration is extensible
	 */
} e_VehicleTypeEU;

/* VehicleTypeEU */
typedef long	 VehicleTypeEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VehicleTypeEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VehicleTypeEU;
extern const asn_INTEGER_specifics_t asn_SPC_VehicleTypeEU_specs_1;
asn_struct_free_f VehicleTypeEU_free;
asn_struct_print_f VehicleTypeEU_print;
asn_constr_check_f VehicleTypeEU_constraint;
ber_type_decoder_f VehicleTypeEU_decode_ber;
der_type_encoder_f VehicleTypeEU_encode_der;
xer_type_decoder_f VehicleTypeEU_decode_xer;
xer_type_encoder_f VehicleTypeEU_encode_xer;
oer_type_decoder_f VehicleTypeEU_decode_oer;
oer_type_encoder_f VehicleTypeEU_encode_oer;
per_type_decoder_f VehicleTypeEU_decode_uper;
per_type_encoder_f VehicleTypeEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleTypeEU_H_ */
#include "asn_internal.h"
