/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_WaitOnStoplineEU_H_
#define	_WaitOnStoplineEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"

#ifdef __cplusplus
extern "C" {
#endif

/* WaitOnStoplineEU */
typedef BOOLEAN_t	 WaitOnStoplineEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WaitOnStoplineEU;
asn_struct_free_f WaitOnStoplineEU_free;
asn_struct_print_f WaitOnStoplineEU_print;
asn_constr_check_f WaitOnStoplineEU_constraint;
ber_type_decoder_f WaitOnStoplineEU_decode_ber;
der_type_encoder_f WaitOnStoplineEU_encode_der;
xer_type_decoder_f WaitOnStoplineEU_decode_xer;
xer_type_encoder_f WaitOnStoplineEU_encode_xer;
oer_type_decoder_f WaitOnStoplineEU_decode_oer;
oer_type_encoder_f WaitOnStoplineEU_encode_oer;
per_type_decoder_f WaitOnStoplineEU_decode_uper;
per_type_encoder_f WaitOnStoplineEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _WaitOnStoplineEU_H_ */
#include "asn_internal.h"
