/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_AdvisorySpeedTypeEU_H_
#define	_AdvisorySpeedTypeEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AdvisorySpeedTypeEU {
	AdvisorySpeedTypeEU_none	= 0,
	AdvisorySpeedTypeEU_greenwave	= 1,
	AdvisorySpeedTypeEU_ecoDrive	= 2,
	AdvisorySpeedTypeEU_transit	= 3
	/*
	 * Enumeration is extensible
	 */
} e_AdvisorySpeedTypeEU;

/* AdvisorySpeedTypeEU */
typedef long	 AdvisorySpeedTypeEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AdvisorySpeedTypeEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AdvisorySpeedTypeEU;
extern const asn_INTEGER_specifics_t asn_SPC_AdvisorySpeedTypeEU_specs_1;
asn_struct_free_f AdvisorySpeedTypeEU_free;
asn_struct_print_f AdvisorySpeedTypeEU_print;
asn_constr_check_f AdvisorySpeedTypeEU_constraint;
ber_type_decoder_f AdvisorySpeedTypeEU_decode_ber;
der_type_encoder_f AdvisorySpeedTypeEU_encode_der;
xer_type_decoder_f AdvisorySpeedTypeEU_decode_xer;
xer_type_encoder_f AdvisorySpeedTypeEU_encode_xer;
oer_type_decoder_f AdvisorySpeedTypeEU_decode_oer;
oer_type_encoder_f AdvisorySpeedTypeEU_encode_oer;
per_type_decoder_f AdvisorySpeedTypeEU_decode_uper;
per_type_encoder_f AdvisorySpeedTypeEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AdvisorySpeedTypeEU_H_ */
#include "asn_internal.h"
