/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_AllowedManeuversEU_H_
#define	_AllowedManeuversEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AllowedManeuversEU {
	AllowedManeuversEU_maneuverStraightAllowed	= 0,
	AllowedManeuversEU_maneuverLeftAllowed	= 1,
	AllowedManeuversEU_maneuverRightAllowed	= 2,
	AllowedManeuversEU_maneuverUTurnAllowed	= 3,
	AllowedManeuversEU_maneuverLeftTurnOnRedAllowed	= 4,
	AllowedManeuversEU_maneuverRightTurnOnRedAllowed	= 5,
	AllowedManeuversEU_maneuverLaneChangeAllowed	= 6,
	AllowedManeuversEU_maneuverNoStoppingAllowed	= 7,
	AllowedManeuversEU_yieldAllwaysRequired	= 8,
	AllowedManeuversEU_goWithHalt	= 9,
	AllowedManeuversEU_caution	= 10,
	AllowedManeuversEU_reserved1	= 11
} e_AllowedManeuversEU;

/* AllowedManeuversEU */
typedef BIT_STRING_t	 AllowedManeuversEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AllowedManeuversEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AllowedManeuversEU;
asn_struct_free_f AllowedManeuversEU_free;
asn_struct_print_f AllowedManeuversEU_print;
asn_constr_check_f AllowedManeuversEU_constraint;
ber_type_decoder_f AllowedManeuversEU_decode_ber;
der_type_encoder_f AllowedManeuversEU_encode_der;
xer_type_decoder_f AllowedManeuversEU_decode_xer;
xer_type_encoder_f AllowedManeuversEU_encode_xer;
oer_type_decoder_f AllowedManeuversEU_decode_oer;
oer_type_encoder_f AllowedManeuversEU_encode_oer;
per_type_decoder_f AllowedManeuversEU_decode_uper;
per_type_encoder_f AllowedManeuversEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AllowedManeuversEU_H_ */
#include "asn_internal.h"
