/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "AntennaOffsetSetEU.h"

asn_TYPE_member_t asn_MBR_AntennaOffsetSetEU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AntennaOffsetSetEU, antOffsetX),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Offset_B12EU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"antOffsetX"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AntennaOffsetSetEU, antOffsetY),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Offset_B09EU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"antOffsetY"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AntennaOffsetSetEU, antOffsetZ),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Offset_B10EU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"antOffsetZ"
		},
};
static const ber_tlv_tag_t asn_DEF_AntennaOffsetSetEU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AntennaOffsetSetEU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* antOffsetX */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* antOffsetY */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* antOffsetZ */
};
asn_SEQUENCE_specifics_t asn_SPC_AntennaOffsetSetEU_specs_1 = {
	sizeof(struct AntennaOffsetSetEU),
	offsetof(struct AntennaOffsetSetEU, _asn_ctx),
	asn_MAP_AntennaOffsetSetEU_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AntennaOffsetSetEU = {
	"AntennaOffsetSetEU",
	"AntennaOffsetSetEU",
	&asn_OP_SEQUENCE,
	asn_DEF_AntennaOffsetSetEU_tags_1,
	sizeof(asn_DEF_AntennaOffsetSetEU_tags_1)
		/sizeof(asn_DEF_AntennaOffsetSetEU_tags_1[0]), /* 1 */
	asn_DEF_AntennaOffsetSetEU_tags_1,	/* Same as above */
	sizeof(asn_DEF_AntennaOffsetSetEU_tags_1)
		/sizeof(asn_DEF_AntennaOffsetSetEU_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AntennaOffsetSetEU_1,
	3,	/* Elements count */
	&asn_SPC_AntennaOffsetSetEU_specs_1	/* Additional specs */
};

