/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_BasicVehicleRoleEU_H_
#define	_BasicVehicleRoleEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BasicVehicleRoleEU {
	BasicVehicleRoleEU_basicVehicle	= 0,
	BasicVehicleRoleEU_publicTransport	= 1,
	BasicVehicleRoleEU_specialTransport	= 2,
	BasicVehicleRoleEU_dangerousGoods	= 3,
	BasicVehicleRoleEU_roadWork	= 4,
	BasicVehicleRoleEU_roadRescue	= 5,
	BasicVehicleRoleEU_emergency	= 6,
	BasicVehicleRoleEU_safetyCar	= 7,
	BasicVehicleRoleEU_none_unknown	= 8,
	BasicVehicleRoleEU_truck	= 9,
	BasicVehicleRoleEU_motorcycle	= 10,
	BasicVehicleRoleEU_roadSideSource	= 11,
	BasicVehicleRoleEU_police	= 12,
	BasicVehicleRoleEU_fire	= 13,
	BasicVehicleRoleEU_ambulance	= 14,
	BasicVehicleRoleEU_dot	= 15,
	BasicVehicleRoleEU_transit	= 16,
	BasicVehicleRoleEU_slowMoving	= 17,
	BasicVehicleRoleEU_stopNgo	= 18,
	BasicVehicleRoleEU_cyclist	= 19,
	BasicVehicleRoleEU_pedestrian	= 20,
	BasicVehicleRoleEU_nonMotorized	= 21,
	BasicVehicleRoleEU_military	= 22
	/*
	 * Enumeration is extensible
	 */
} e_BasicVehicleRoleEU;

/* BasicVehicleRoleEU */
typedef long	 BasicVehicleRoleEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_BasicVehicleRoleEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_BasicVehicleRoleEU;
extern const asn_INTEGER_specifics_t asn_SPC_BasicVehicleRoleEU_specs_1;
asn_struct_free_f BasicVehicleRoleEU_free;
asn_struct_print_f BasicVehicleRoleEU_print;
asn_constr_check_f BasicVehicleRoleEU_constraint;
ber_type_decoder_f BasicVehicleRoleEU_decode_ber;
der_type_encoder_f BasicVehicleRoleEU_encode_der;
xer_type_decoder_f BasicVehicleRoleEU_decode_xer;
xer_type_encoder_f BasicVehicleRoleEU_encode_xer;
oer_type_decoder_f BasicVehicleRoleEU_decode_oer;
oer_type_encoder_f BasicVehicleRoleEU_encode_oer;
per_type_decoder_f BasicVehicleRoleEU_decode_uper;
per_type_encoder_f BasicVehicleRoleEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BasicVehicleRoleEU_H_ */
#include "asn_internal.h"
