/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ElevationConfidenceEU_H_
#define	_ElevationConfidenceEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ElevationConfidenceEU {
	ElevationConfidenceEU_unavailable	= 0,
	ElevationConfidenceEU_elev_500_00	= 1,
	ElevationConfidenceEU_elev_200_00	= 2,
	ElevationConfidenceEU_elev_100_00	= 3,
	ElevationConfidenceEU_elev_050_00	= 4,
	ElevationConfidenceEU_elev_020_00	= 5,
	ElevationConfidenceEU_elev_010_00	= 6,
	ElevationConfidenceEU_elev_005_00	= 7,
	ElevationConfidenceEU_elev_002_00	= 8,
	ElevationConfidenceEU_elev_001_00	= 9,
	ElevationConfidenceEU_elev_000_50	= 10,
	ElevationConfidenceEU_elev_000_20	= 11,
	ElevationConfidenceEU_elev_000_10	= 12,
	ElevationConfidenceEU_elev_000_05	= 13,
	ElevationConfidenceEU_elev_000_02	= 14,
	ElevationConfidenceEU_elev_000_01	= 15
} e_ElevationConfidenceEU;

/* ElevationConfidenceEU */
typedef long	 ElevationConfidenceEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ElevationConfidenceEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ElevationConfidenceEU;
extern const asn_INTEGER_specifics_t asn_SPC_ElevationConfidenceEU_specs_1;
asn_struct_free_f ElevationConfidenceEU_free;
asn_struct_print_f ElevationConfidenceEU_print;
asn_constr_check_f ElevationConfidenceEU_constraint;
ber_type_decoder_f ElevationConfidenceEU_decode_ber;
der_type_encoder_f ElevationConfidenceEU_encode_der;
xer_type_decoder_f ElevationConfidenceEU_decode_xer;
xer_type_encoder_f ElevationConfidenceEU_encode_xer;
oer_type_decoder_f ElevationConfidenceEU_decode_oer;
oer_type_encoder_f ElevationConfidenceEU_encode_oer;
per_type_decoder_f ElevationConfidenceEU_decode_uper;
per_type_encoder_f ElevationConfidenceEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ElevationConfidenceEU_H_ */
#include "asn_internal.h"
