/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_EmissionTypeEU_H_
#define	_EmissionTypeEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EmissionTypeEU {
	EmissionTypeEU_euro1	= 0,
	EmissionTypeEU_euro2	= 1,
	EmissionTypeEU_euro3	= 2,
	EmissionTypeEU_euro4	= 3,
	EmissionTypeEU_euro5	= 4,
	EmissionTypeEU_euro6	= 5
	/*
	 * Enumeration is extensible
	 */
} e_EmissionTypeEU;

/* EmissionTypeEU */
typedef long	 EmissionTypeEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EmissionTypeEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EmissionTypeEU;
extern const asn_INTEGER_specifics_t asn_SPC_EmissionTypeEU_specs_1;
asn_struct_free_f EmissionTypeEU_free;
asn_struct_print_f EmissionTypeEU_print;
asn_constr_check_f EmissionTypeEU_constraint;
ber_type_decoder_f EmissionTypeEU_decode_ber;
der_type_encoder_f EmissionTypeEU_encode_der;
xer_type_decoder_f EmissionTypeEU_decode_xer;
xer_type_encoder_f EmissionTypeEU_encode_xer;
oer_type_decoder_f EmissionTypeEU_decode_oer;
oer_type_encoder_f EmissionTypeEU_encode_oer;
per_type_decoder_f EmissionTypeEU_decode_uper;
per_type_encoder_f EmissionTypeEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EmissionTypeEU_H_ */
#include "asn_internal.h"
