/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions-NEW"
 * 	found in "../../cpm/F/kell/asd/with_riebl/CPM_NEW.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_FreeSpaceAddendum_H_
#define	_FreeSpaceAddendum_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FreeSpaceConfidence.h"
#include "FreeSpaceArea.h"
#include "Identifier.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FreeSpaceAddendum */
typedef struct FreeSpaceAddendum {
	FreeSpaceConfidence_t	 freeSpaceConfidence;
	FreeSpaceArea_t	 freeSpaceArea;
	struct FreeSpaceAddendum__sensorID {
		A_SEQUENCE_OF(Identifier_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sensorID;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FreeSpaceAddendum_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FreeSpaceAddendum;
extern asn_SEQUENCE_specifics_t asn_SPC_FreeSpaceAddendum_specs_1;
extern asn_TYPE_member_t asn_MBR_FreeSpaceAddendum_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _FreeSpaceAddendum_H_ */
#include "asn_internal.h"
