/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_GenericLaneEU_H_
#define	_GenericLaneEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LaneIDEU.h"
#include "DescriptiveNameEU.h"
#include "ApproachIDEU.h"
#include "LaneAttributesEU.h"
#include "AllowedManeuversEU.h"
#include "NodeListXYEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ConnectsToListEU;
struct OverlayLaneListEU;
struct RegionalExtensionEU;

/* GenericLaneEU */
typedef struct GenericLaneEU {
	LaneIDEU_t	 laneID;
	DescriptiveNameEU_t	*name	/* OPTIONAL */;
	ApproachIDEU_t	*ingressApproach	/* OPTIONAL */;
	ApproachIDEU_t	*egressApproach	/* OPTIONAL */;
	LaneAttributesEU_t	 laneAttributes;
	AllowedManeuversEU_t	*maneuvers	/* OPTIONAL */;
	NodeListXYEU_t	 nodeList;
	struct ConnectsToListEU	*connectsTo	/* OPTIONAL */;
	struct OverlayLaneListEU	*overlays	/* OPTIONAL */;
	struct GenericLaneEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GenericLaneEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GenericLaneEU;
extern asn_SEQUENCE_specifics_t asn_SPC_GenericLaneEU_specs_1;
extern asn_TYPE_member_t asn_MBR_GenericLaneEU_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ConnectsToListEU.h"
#include "OverlayLaneListEU.h"
#include "RegionalExtensionEU.h"

#endif	/* _GenericLaneEU_H_ */
#include "asn_internal.h"
