/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_LaneAttributes_SidewalkEU_H_
#define	_LaneAttributes_SidewalkEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LaneAttributes_SidewalkEU {
	LaneAttributes_SidewalkEU_sidewalk_RevocableLane	= 0,
	LaneAttributes_SidewalkEU_bicyleUseAllowed	= 1,
	LaneAttributes_SidewalkEU_isSidewalkFlyOverLane	= 2,
	LaneAttributes_SidewalkEU_walkBikes	= 3
} e_LaneAttributes_SidewalkEU;

/* LaneAttributes-SidewalkEU */
typedef BIT_STRING_t	 LaneAttributes_SidewalkEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LaneAttributes_SidewalkEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LaneAttributes_SidewalkEU;
asn_struct_free_f LaneAttributes_SidewalkEU_free;
asn_struct_print_f LaneAttributes_SidewalkEU_print;
asn_constr_check_f LaneAttributes_SidewalkEU_constraint;
ber_type_decoder_f LaneAttributes_SidewalkEU_decode_ber;
der_type_encoder_f LaneAttributes_SidewalkEU_encode_der;
xer_type_decoder_f LaneAttributes_SidewalkEU_decode_xer;
xer_type_encoder_f LaneAttributes_SidewalkEU_encode_xer;
oer_type_decoder_f LaneAttributes_SidewalkEU_decode_oer;
oer_type_encoder_f LaneAttributes_SidewalkEU_encode_oer;
per_type_decoder_f LaneAttributes_SidewalkEU_decode_uper;
per_type_encoder_f LaneAttributes_SidewalkEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LaneAttributes_SidewalkEU_H_ */
#include "asn_internal.h"
