/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "LaneAttributesEU-addGrpCEU.h"

static asn_TYPE_member_t asn_MBR_LaneAttributesEU_addGrpCEU_1[] = {
	{ ATF_POINTER, 2, offsetof(struct LaneAttributesEU_addGrpCEU, maxVehicleHeight),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleHeightEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maxVehicleHeight"
		},
	{ ATF_POINTER, 1, offsetof(struct LaneAttributesEU_addGrpCEU, maxVehicleWeight),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleMassEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maxVehicleWeight"
		},
};
static const int asn_MAP_LaneAttributesEU_addGrpCEU_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_LaneAttributesEU_addGrpCEU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LaneAttributesEU_addGrpCEU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* maxVehicleHeight */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* maxVehicleWeight */
};
static asn_SEQUENCE_specifics_t asn_SPC_LaneAttributesEU_addGrpCEU_specs_1 = {
	sizeof(struct LaneAttributesEU_addGrpCEU),
	offsetof(struct LaneAttributesEU_addGrpCEU, _asn_ctx),
	asn_MAP_LaneAttributesEU_addGrpCEU_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_LaneAttributesEU_addGrpCEU_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LaneAttributesEU_addGrpCEU = {
	"LaneAttributesEU-addGrpCEU",
	"LaneAttributesEU-addGrpCEU",
	&asn_OP_SEQUENCE,
	asn_DEF_LaneAttributesEU_addGrpCEU_tags_1,
	sizeof(asn_DEF_LaneAttributesEU_addGrpCEU_tags_1)
		/sizeof(asn_DEF_LaneAttributesEU_addGrpCEU_tags_1[0]), /* 1 */
	asn_DEF_LaneAttributesEU_addGrpCEU_tags_1,	/* Same as above */
	sizeof(asn_DEF_LaneAttributesEU_addGrpCEU_tags_1)
		/sizeof(asn_DEF_LaneAttributesEU_addGrpCEU_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LaneAttributesEU_addGrpCEU_1,
	2,	/* Elements count */
	&asn_SPC_LaneAttributesEU_addGrpCEU_specs_1	/* Additional specs */
};

