/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_LaneAttributes_BikeEU_H_
#define	_LaneAttributes_BikeEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LaneAttributes_BikeEU {
	LaneAttributes_BikeEU_bikeRevocableLane	= 0,
	LaneAttributes_BikeEU_pedestrianUseAllowed	= 1,
	LaneAttributes_BikeEU_isBikeFlyOverLane	= 2,
	LaneAttributes_BikeEU_fixedCycleTime	= 3,
	LaneAttributes_BikeEU_biDirectionalCycleTimes	= 4,
	LaneAttributes_BikeEU_isolatedByBarrier	= 5,
	LaneAttributes_BikeEU_unsignalizedSegmentsPresent	= 6
} e_LaneAttributes_BikeEU;

/* LaneAttributes-BikeEU */
typedef BIT_STRING_t	 LaneAttributes_BikeEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LaneAttributes_BikeEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LaneAttributes_BikeEU;
asn_struct_free_f LaneAttributes_BikeEU_free;
asn_struct_print_f LaneAttributes_BikeEU_print;
asn_constr_check_f LaneAttributes_BikeEU_constraint;
ber_type_decoder_f LaneAttributes_BikeEU_decode_ber;
der_type_encoder_f LaneAttributes_BikeEU_encode_der;
xer_type_decoder_f LaneAttributes_BikeEU_decode_xer;
xer_type_encoder_f LaneAttributes_BikeEU_encode_xer;
oer_type_decoder_f LaneAttributes_BikeEU_decode_oer;
oer_type_encoder_f LaneAttributes_BikeEU_encode_oer;
per_type_decoder_f LaneAttributes_BikeEU_decode_uper;
per_type_encoder_f LaneAttributes_BikeEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LaneAttributes_BikeEU_H_ */
#include "asn_internal.h"
