/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "LaneAttributesEU.h"

asn_TYPE_member_t asn_MBR_LaneAttributesEU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LaneAttributesEU, directionalUse),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneDirectionEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"directionalUse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaneAttributesEU, sharedWith),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneSharingEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sharedWith"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaneAttributesEU, laneType),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_LaneTypeAttributesEU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"laneType"
		},
	{ ATF_POINTER, 1, offsetof(struct LaneAttributesEU, regional),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RegionalExtensionEU_329P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"regional"
		},
};
static const int asn_MAP_LaneAttributesEU_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_LaneAttributesEU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LaneAttributesEU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* directionalUse */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sharedWith */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* laneType */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* regional */
};
asn_SEQUENCE_specifics_t asn_SPC_LaneAttributesEU_specs_1 = {
	sizeof(struct LaneAttributesEU),
	offsetof(struct LaneAttributesEU, _asn_ctx),
	asn_MAP_LaneAttributesEU_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_LaneAttributesEU_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LaneAttributesEU = {
	"LaneAttributesEU",
	"LaneAttributesEU",
	&asn_OP_SEQUENCE,
	asn_DEF_LaneAttributesEU_tags_1,
	sizeof(asn_DEF_LaneAttributesEU_tags_1)
		/sizeof(asn_DEF_LaneAttributesEU_tags_1[0]), /* 1 */
	asn_DEF_LaneAttributesEU_tags_1,	/* Same as above */
	sizeof(asn_DEF_LaneAttributesEU_tags_1)
		/sizeof(asn_DEF_LaneAttributesEU_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LaneAttributesEU_1,
	4,	/* Elements count */
	&asn_SPC_LaneAttributesEU_specs_1	/* Additional specs */
};

