/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_LaneAttributes_ParkingEU_H_
#define	_LaneAttributes_ParkingEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LaneAttributes_ParkingEU {
	LaneAttributes_ParkingEU_parkingRevocableLane	= 0,
	LaneAttributes_ParkingEU_parallelParkingInUse	= 1,
	LaneAttributes_ParkingEU_headInParkingInUse	= 2,
	LaneAttributes_ParkingEU_doNotParkZone	= 3,
	LaneAttributes_ParkingEU_parkingForBusUse	= 4,
	LaneAttributes_ParkingEU_parkingForTaxiUse	= 5,
	LaneAttributes_ParkingEU_noPublicParkingUse	= 6
} e_LaneAttributes_ParkingEU;

/* LaneAttributes-ParkingEU */
typedef BIT_STRING_t	 LaneAttributes_ParkingEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LaneAttributes_ParkingEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LaneAttributes_ParkingEU;
asn_struct_free_f LaneAttributes_ParkingEU_free;
asn_struct_print_f LaneAttributes_ParkingEU_print;
asn_constr_check_f LaneAttributes_ParkingEU_constraint;
ber_type_decoder_f LaneAttributes_ParkingEU_decode_ber;
der_type_encoder_f LaneAttributes_ParkingEU_encode_der;
xer_type_decoder_f LaneAttributes_ParkingEU_decode_xer;
xer_type_encoder_f LaneAttributes_ParkingEU_encode_xer;
oer_type_decoder_f LaneAttributes_ParkingEU_decode_oer;
oer_type_encoder_f LaneAttributes_ParkingEU_encode_oer;
per_type_decoder_f LaneAttributes_ParkingEU_decode_uper;
per_type_encoder_f LaneAttributes_ParkingEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LaneAttributes_ParkingEU_H_ */
#include "asn_internal.h"
