/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_LaneAttributes_BarrierEU_H_
#define	_LaneAttributes_BarrierEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LaneAttributes_BarrierEU {
	LaneAttributes_BarrierEU_median_RevocableLane	= 0,
	LaneAttributes_BarrierEU_median	= 1,
	LaneAttributes_BarrierEU_whiteLineHashing	= 2,
	LaneAttributes_BarrierEU_stripedLines	= 3,
	LaneAttributes_BarrierEU_doubleStripedLines	= 4,
	LaneAttributes_BarrierEU_trafficCones	= 5,
	LaneAttributes_BarrierEU_constructionBarrier	= 6,
	LaneAttributes_BarrierEU_trafficChannels	= 7,
	LaneAttributes_BarrierEU_lowCurbs	= 8,
	LaneAttributes_BarrierEU_highCurbs	= 9
} e_LaneAttributes_BarrierEU;

/* LaneAttributes-BarrierEU */
typedef BIT_STRING_t	 LaneAttributes_BarrierEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LaneAttributes_BarrierEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LaneAttributes_BarrierEU;
asn_struct_free_f LaneAttributes_BarrierEU_free;
asn_struct_print_f LaneAttributes_BarrierEU_print;
asn_constr_check_f LaneAttributes_BarrierEU_constraint;
ber_type_decoder_f LaneAttributes_BarrierEU_decode_ber;
der_type_encoder_f LaneAttributes_BarrierEU_encode_der;
xer_type_decoder_f LaneAttributes_BarrierEU_decode_xer;
xer_type_encoder_f LaneAttributes_BarrierEU_encode_xer;
oer_type_decoder_f LaneAttributes_BarrierEU_decode_oer;
oer_type_encoder_f LaneAttributes_BarrierEU_encode_oer;
per_type_decoder_f LaneAttributes_BarrierEU_decode_uper;
per_type_encoder_f LaneAttributes_BarrierEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LaneAttributes_BarrierEU_H_ */
#include "asn_internal.h"
