/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_LaneDataAttributeEU_H_
#define	_LaneDataAttributeEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DeltaAngleEU.h"
#include "RoadwayCrownAngleEU.h"
#include "MergeDivergeNodeAngleEU.h"
#include "SpeedLimitListEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LaneDataAttributeEU_PR {
	LaneDataAttributeEU_PR_NOTHING,	/* No components present */
	LaneDataAttributeEU_PR_pathEndPointAngle,
	LaneDataAttributeEU_PR_laneCrownPointCenter,
	LaneDataAttributeEU_PR_laneCrownPointLeft,
	LaneDataAttributeEU_PR_laneCrownPointRight,
	LaneDataAttributeEU_PR_laneAngle,
	LaneDataAttributeEU_PR_speedLimits,
	LaneDataAttributeEU_PR_regional
	/* Extensions may appear below */
	
} LaneDataAttributeEU_PR;

/* Forward declarations */
struct RegionalExtensionEU;

/* LaneDataAttributeEU */
typedef struct LaneDataAttributeEU {
	LaneDataAttributeEU_PR present;
	union LaneDataAttributeEU_u {
		DeltaAngleEU_t	 pathEndPointAngle;
		RoadwayCrownAngleEU_t	 laneCrownPointCenter;
		RoadwayCrownAngleEU_t	 laneCrownPointLeft;
		RoadwayCrownAngleEU_t	 laneCrownPointRight;
		MergeDivergeNodeAngleEU_t	 laneAngle;
		SpeedLimitListEU_t	 speedLimits;
		struct LaneDataAttributeEU__regional {
			A_SEQUENCE_OF(struct RegionalExtensionEU) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} regional;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LaneDataAttributeEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaneDataAttributeEU;
extern asn_CHOICE_specifics_t asn_SPC_LaneDataAttributeEU_specs_1;
extern asn_TYPE_member_t asn_MBR_LaneDataAttributeEU_1[7];
extern asn_per_constraints_t asn_PER_type_LaneDataAttributeEU_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RegionalExtensionEU.h"

#endif	/* _LaneDataAttributeEU_H_ */
#include "asn_internal.h"
