/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_LaneTypeAttributesEU_H_
#define	_LaneTypeAttributesEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LaneAttributes-VehicleEU.h"
#include "LaneAttributes-CrosswalkEU.h"
#include "LaneAttributes-BikeEU.h"
#include "LaneAttributes-SidewalkEU.h"
#include "LaneAttributes-BarrierEU.h"
#include "LaneAttributes-StripingEU.h"
#include "LaneAttributes-TrackedVehicleEU.h"
#include "LaneAttributes-ParkingEU.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LaneTypeAttributesEU_PR {
	LaneTypeAttributesEU_PR_NOTHING,	/* No components present */
	LaneTypeAttributesEU_PR_vehicle,
	LaneTypeAttributesEU_PR_crosswalk,
	LaneTypeAttributesEU_PR_bikeLane,
	LaneTypeAttributesEU_PR_sidewalk,
	LaneTypeAttributesEU_PR_median,
	LaneTypeAttributesEU_PR_striping,
	LaneTypeAttributesEU_PR_trackedVehicle,
	LaneTypeAttributesEU_PR_parking
	/* Extensions may appear below */
	
} LaneTypeAttributesEU_PR;

/* LaneTypeAttributesEU */
typedef struct LaneTypeAttributesEU {
	LaneTypeAttributesEU_PR present;
	union LaneTypeAttributesEU_u {
		LaneAttributes_VehicleEU_t	 vehicle;
		LaneAttributes_CrosswalkEU_t	 crosswalk;
		LaneAttributes_BikeEU_t	 bikeLane;
		LaneAttributes_SidewalkEU_t	 sidewalk;
		LaneAttributes_BarrierEU_t	 median;
		LaneAttributes_StripingEU_t	 striping;
		LaneAttributes_TrackedVehicleEU_t	 trackedVehicle;
		LaneAttributes_ParkingEU_t	 parking;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LaneTypeAttributesEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaneTypeAttributesEU;
extern asn_CHOICE_specifics_t asn_SPC_LaneTypeAttributesEU_specs_1;
extern asn_TYPE_member_t asn_MBR_LaneTypeAttributesEU_1[8];
extern asn_per_constraints_t asn_PER_type_LaneTypeAttributesEU_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LaneTypeAttributesEU_H_ */
#include "asn_internal.h"
