/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_LayerTypeEU_H_
#define	_LayerTypeEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LayerTypeEU {
	LayerTypeEU_none	= 0,
	LayerTypeEU_mixedContent	= 1,
	LayerTypeEU_generalMapData	= 2,
	LayerTypeEU_intersectionData	= 3,
	LayerTypeEU_curveData	= 4,
	LayerTypeEU_roadwaySectionData	= 5,
	LayerTypeEU_parkingAreaData	= 6,
	LayerTypeEU_sharedLaneData	= 7
	/*
	 * Enumeration is extensible
	 */
} e_LayerTypeEU;

/* LayerTypeEU */
typedef long	 LayerTypeEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LayerTypeEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LayerTypeEU;
extern const asn_INTEGER_specifics_t asn_SPC_LayerTypeEU_specs_1;
asn_struct_free_f LayerTypeEU_free;
asn_struct_print_f LayerTypeEU_print;
asn_constr_check_f LayerTypeEU_constraint;
ber_type_decoder_f LayerTypeEU_decode_ber;
der_type_encoder_f LayerTypeEU_encode_der;
xer_type_decoder_f LayerTypeEU_decode_xer;
xer_type_encoder_f LayerTypeEU_encode_xer;
oer_type_decoder_f LayerTypeEU_decode_oer;
oer_type_encoder_f LayerTypeEU_encode_oer;
per_type_decoder_f LayerTypeEU_decode_uper;
per_type_encoder_f LayerTypeEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LayerTypeEU_H_ */
#include "asn_internal.h"
