/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_NodeXYEU_H_
#define	_NodeXYEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NodeOffsetPointXYEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NodeAttributeSetXYEU;

/* NodeXYEU */
typedef struct NodeXYEU {
	NodeOffsetPointXYEU_t	 delta;
	struct NodeAttributeSetXYEU	*attributes	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NodeXYEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeXYEU;
extern asn_SEQUENCE_specifics_t asn_SPC_NodeXYEU_specs_1;
extern asn_TYPE_member_t asn_MBR_NodeXYEU_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NodeAttributeSetXYEU.h"

#endif	/* _NodeXYEU_H_ */
#include "asn_internal.h"
