/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions-NEW"
 * 	found in "../../cpm/F/kell/asd/with_riebl/CPM_NEW.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_OtherSubclass_H_
#define	_OtherSubclass_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "ClassConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OtherSubclass__type {
	OtherSubclass__type_unknown	= 0,
	OtherSubclass__type_small	= 1,
	OtherSubclass__type_medium	= 2,
	OtherSubclass__type_large	= 3,
	OtherSubclass__type_roadSideUnit	= 4
} e_OtherSubclass__type;

/* OtherSubclass */
typedef struct OtherSubclass {
	long	*type	/* OPTIONAL */;
	ClassConfidence_t	*confidence	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OtherSubclass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OtherSubclass;
extern asn_SEQUENCE_specifics_t asn_SPC_OtherSubclass_specs_1;
extern asn_TYPE_member_t asn_MBR_OtherSubclass_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _OtherSubclass_H_ */
#include "asn_internal.h"
