/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PedestrianBicycleDetectEU_H_
#define	_PedestrianBicycleDetectEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PedestrianBicycleDetectEU */
typedef BOOLEAN_t	 PedestrianBicycleDetectEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PedestrianBicycleDetectEU;
asn_struct_free_f PedestrianBicycleDetectEU_free;
asn_struct_print_f PedestrianBicycleDetectEU_print;
asn_constr_check_f PedestrianBicycleDetectEU_constraint;
ber_type_decoder_f PedestrianBicycleDetectEU_decode_ber;
der_type_encoder_f PedestrianBicycleDetectEU_encode_der;
xer_type_decoder_f PedestrianBicycleDetectEU_decode_xer;
xer_type_encoder_f PedestrianBicycleDetectEU_encode_xer;
oer_type_decoder_f PedestrianBicycleDetectEU_decode_oer;
oer_type_encoder_f PedestrianBicycleDetectEU_encode_oer;
per_type_decoder_f PedestrianBicycleDetectEU_decode_uper;
per_type_encoder_f PedestrianBicycleDetectEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PedestrianBicycleDetectEU_H_ */
#include "asn_internal.h"
