/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PositionalAccuracyEU_H_
#define	_PositionalAccuracyEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SemiMajorAxisAccuracyEU.h"
#include "SemiMinorAxisAccuracyEU.h"
#include "SemiMajorAxisOrientationEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PositionalAccuracyEU */
typedef struct PositionalAccuracyEU {
	SemiMajorAxisAccuracyEU_t	 semiMajor;
	SemiMinorAxisAccuracyEU_t	 semiMinor;
	SemiMajorAxisOrientationEU_t	 orientation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PositionalAccuracyEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionalAccuracyEU;
extern asn_SEQUENCE_specifics_t asn_SPC_PositionalAccuracyEU_specs_1;
extern asn_TYPE_member_t asn_MBR_PositionalAccuracyEU_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _PositionalAccuracyEU_H_ */
#include "asn_internal.h"
