/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "Position3DEU-addGrpCEU.h"

static asn_TYPE_member_t asn_MBR_Position3DEU_addGrpCEU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Position3DEU_addGrpCEU, altitude),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Altitude,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"altitude"
		},
};
static const ber_tlv_tag_t asn_DEF_Position3DEU_addGrpCEU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Position3DEU_addGrpCEU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* altitude */
};
static asn_SEQUENCE_specifics_t asn_SPC_Position3DEU_addGrpCEU_specs_1 = {
	sizeof(struct Position3DEU_addGrpCEU),
	offsetof(struct Position3DEU_addGrpCEU, _asn_ctx),
	asn_MAP_Position3DEU_addGrpCEU_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Position3DEU_addGrpCEU = {
	"Position3DEU-addGrpCEU",
	"Position3DEU-addGrpCEU",
	&asn_OP_SEQUENCE,
	asn_DEF_Position3DEU_addGrpCEU_tags_1,
	sizeof(asn_DEF_Position3DEU_addGrpCEU_tags_1)
		/sizeof(asn_DEF_Position3DEU_addGrpCEU_tags_1[0]), /* 1 */
	asn_DEF_Position3DEU_addGrpCEU_tags_1,	/* Same as above */
	sizeof(asn_DEF_Position3DEU_addGrpCEU_tags_1)
		/sizeof(asn_DEF_Position3DEU_addGrpCEU_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Position3DEU_addGrpCEU_1,
	1,	/* Elements count */
	&asn_SPC_Position3DEU_addGrpCEU_specs_1	/* Additional specs */
};

