/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_Position3DEU_H_
#define	_Position3DEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Latitude.h"
#include "Longitude.h"
#include "ElevationEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RegionalExtensionEU;

/* Position3DEU */
typedef struct Position3DEU {
	Latitude_t	 lat;
	Longitude_t	 Long;
	ElevationEU_t	*elevation	/* OPTIONAL */;
	struct Position3DEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Position3DEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Position3DEU;
extern asn_SEQUENCE_specifics_t asn_SPC_Position3DEU_specs_1;
extern asn_TYPE_member_t asn_MBR_Position3DEU_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RegionalExtensionEU.h"

#endif	/* _Position3DEU_H_ */
#include "asn_internal.h"
