/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PrioritizationResponseStatusEU_H_
#define	_PrioritizationResponseStatusEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PrioritizationResponseStatusEU {
	PrioritizationResponseStatusEU_unknown	= 0,
	PrioritizationResponseStatusEU_requested	= 1,
	PrioritizationResponseStatusEU_processing	= 2,
	PrioritizationResponseStatusEU_watchOtherTraffic	= 3,
	PrioritizationResponseStatusEU_granted	= 4,
	PrioritizationResponseStatusEU_rejected	= 5,
	PrioritizationResponseStatusEU_maxPresence	= 6,
	PrioritizationResponseStatusEU_reserviceLocked	= 7
	/*
	 * Enumeration is extensible
	 */
} e_PrioritizationResponseStatusEU;

/* PrioritizationResponseStatusEU */
typedef long	 PrioritizationResponseStatusEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PrioritizationResponseStatusEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PrioritizationResponseStatusEU;
extern const asn_INTEGER_specifics_t asn_SPC_PrioritizationResponseStatusEU_specs_1;
asn_struct_free_f PrioritizationResponseStatusEU_free;
asn_struct_print_f PrioritizationResponseStatusEU_print;
asn_constr_check_f PrioritizationResponseStatusEU_constraint;
ber_type_decoder_f PrioritizationResponseStatusEU_decode_ber;
der_type_encoder_f PrioritizationResponseStatusEU_encode_der;
xer_type_decoder_f PrioritizationResponseStatusEU_decode_xer;
xer_type_encoder_f PrioritizationResponseStatusEU_encode_xer;
oer_type_decoder_f PrioritizationResponseStatusEU_decode_oer;
oer_type_encoder_f PrioritizationResponseStatusEU_encode_oer;
per_type_decoder_f PrioritizationResponseStatusEU_decode_uper;
per_type_encoder_f PrioritizationResponseStatusEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PrioritizationResponseStatusEU_H_ */
#include "asn_internal.h"
