/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PrioritizationResponseEU_H_
#define	_PrioritizationResponseEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "StationID.h"
#include "PrioritizationResponseStatusEU.h"
#include "SignalGroupIDEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PrioritizationResponseEU */
typedef struct PrioritizationResponseEU {
	StationID_t	 stationID;
	PrioritizationResponseStatusEU_t	 priorState;
	SignalGroupIDEU_t	 signalGroup;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrioritizationResponseEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrioritizationResponseEU;
extern asn_SEQUENCE_specifics_t asn_SPC_PrioritizationResponseEU_specs_1;
extern asn_TYPE_member_t asn_MBR_PrioritizationResponseEU_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _PrioritizationResponseEU_H_ */
#include "asn_internal.h"
