/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PriorityRequestTypeEU_H_
#define	_PriorityRequestTypeEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PriorityRequestTypeEU {
	PriorityRequestTypeEU_priorityRequestTypeReserved	= 0,
	PriorityRequestTypeEU_priorityRequest	= 1,
	PriorityRequestTypeEU_priorityRequestUpdate	= 2,
	PriorityRequestTypeEU_priorityCancellation	= 3
	/*
	 * Enumeration is extensible
	 */
} e_PriorityRequestTypeEU;

/* PriorityRequestTypeEU */
typedef long	 PriorityRequestTypeEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PriorityRequestTypeEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PriorityRequestTypeEU;
extern const asn_INTEGER_specifics_t asn_SPC_PriorityRequestTypeEU_specs_1;
asn_struct_free_f PriorityRequestTypeEU_free;
asn_struct_print_f PriorityRequestTypeEU_print;
asn_constr_check_f PriorityRequestTypeEU_constraint;
ber_type_decoder_f PriorityRequestTypeEU_decode_ber;
der_type_encoder_f PriorityRequestTypeEU_encode_der;
xer_type_decoder_f PriorityRequestTypeEU_decode_xer;
xer_type_encoder_f PriorityRequestTypeEU_encode_xer;
oer_type_decoder_f PriorityRequestTypeEU_decode_oer;
oer_type_encoder_f PriorityRequestTypeEU_encode_oer;
per_type_decoder_f PriorityRequestTypeEU_decode_uper;
per_type_encoder_f PriorityRequestTypeEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PriorityRequestTypeEU_H_ */
#include "asn_internal.h"
