/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RegionalExtensionEU_H_
#define	_RegionalExtensionEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RegionIdEU.h"
#include "ANY.h"
#include "asn_ioc.h"
#include "OPEN_TYPE.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RegionalExtensionEU_329P0__regExtValue_PR {
	RegionalExtensionEU_329P0__regExtValue_PR_NOTHING,	/* No components present */
	
} RegionalExtensionEU_329P0__regExtValue_PR;

/* RegionalExtensionEU */
typedef struct RegionalExtensionEU_329P0 {
	RegionIdEU_t	 regionId;
	struct RegionalExtensionEU_329P0__regExtValue {
		RegionalExtensionEU_329P0__regExtValue_PR present;
		union RegionalExtensionEU_329P0__regExtValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtensionEU_329P0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtensionEU_329P0;
extern asn_SEQUENCE_specifics_t asn_SPC_RegionalExtensionEU_329P0_specs_1;
extern asn_TYPE_member_t asn_MBR_RegionalExtensionEU_329P0_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RegionalExtensionEU_H_ */
#include "asn_internal.h"
