/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RequestImportanceLevelEU_H_
#define	_RequestImportanceLevelEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RequestImportanceLevelEU {
	RequestImportanceLevelEU_requestImportanceLevelUnKnown	= 0,
	RequestImportanceLevelEU_requestImportanceLevel1	= 1,
	RequestImportanceLevelEU_requestImportanceLevel2	= 2,
	RequestImportanceLevelEU_requestImportanceLevel3	= 3,
	RequestImportanceLevelEU_requestImportanceLevel4	= 4,
	RequestImportanceLevelEU_requestImportanceLevel5	= 5,
	RequestImportanceLevelEU_requestImportanceLevel6	= 6,
	RequestImportanceLevelEU_requestImportanceLevel7	= 7,
	RequestImportanceLevelEU_requestImportanceLevel8	= 8,
	RequestImportanceLevelEU_requestImportanceLevel9	= 9,
	RequestImportanceLevelEU_requestImportanceLevel10	= 10,
	RequestImportanceLevelEU_requestImportanceLevel11	= 11,
	RequestImportanceLevelEU_requestImportanceLevel12	= 12,
	RequestImportanceLevelEU_requestImportanceLevel13	= 13,
	RequestImportanceLevelEU_requestImportanceLevel14	= 14,
	RequestImportanceLevelEU_requestImportanceReserved	= 15
} e_RequestImportanceLevelEU;

/* RequestImportanceLevelEU */
typedef long	 RequestImportanceLevelEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RequestImportanceLevelEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RequestImportanceLevelEU;
extern const asn_INTEGER_specifics_t asn_SPC_RequestImportanceLevelEU_specs_1;
asn_struct_free_f RequestImportanceLevelEU_free;
asn_struct_print_f RequestImportanceLevelEU_print;
asn_constr_check_f RequestImportanceLevelEU_constraint;
ber_type_decoder_f RequestImportanceLevelEU_decode_ber;
der_type_encoder_f RequestImportanceLevelEU_encode_der;
xer_type_decoder_f RequestImportanceLevelEU_decode_xer;
xer_type_encoder_f RequestImportanceLevelEU_encode_xer;
oer_type_decoder_f RequestImportanceLevelEU_decode_oer;
oer_type_encoder_f RequestImportanceLevelEU_encode_oer;
per_type_decoder_f RequestImportanceLevelEU_decode_uper;
per_type_encoder_f RequestImportanceLevelEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RequestImportanceLevelEU_H_ */
#include "asn_internal.h"
