/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RequestorTypeEU_H_
#define	_RequestorTypeEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BasicVehicleRoleEU.h"
#include "RequestSubRoleEU.h"
#include "RequestImportanceLevelEU.h"
#include "Iso3833VehicleType.h"
#include "VehicleTypeEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RegionalExtensionEU;

/* RequestorTypeEU */
typedef struct RequestorTypeEU {
	BasicVehicleRoleEU_t	 role;
	RequestSubRoleEU_t	*subrole	/* OPTIONAL */;
	RequestImportanceLevelEU_t	*request	/* OPTIONAL */;
	Iso3833VehicleType_t	*iso3883	/* OPTIONAL */;
	VehicleTypeEU_t	*hpmsType	/* OPTIONAL */;
	struct RegionalExtensionEU	*regional	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RequestorTypeEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RequestorTypeEU;
extern asn_SEQUENCE_specifics_t asn_SPC_RequestorTypeEU_specs_1;
extern asn_TYPE_member_t asn_MBR_RequestorTypeEU_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RegionalExtensionEU.h"

#endif	/* _RequestorTypeEU_H_ */
#include "asn_internal.h"
