/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RestrictionClassListEU_H_
#define	_RestrictionClassListEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RestrictionClassAssignmentEU;

/* RestrictionClassListEU */
typedef struct RestrictionClassListEU {
	A_SEQUENCE_OF(struct RestrictionClassAssignmentEU) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RestrictionClassListEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RestrictionClassListEU;
extern asn_SET_OF_specifics_t asn_SPC_RestrictionClassListEU_specs_1;
extern asn_TYPE_member_t asn_MBR_RestrictionClassListEU_1[1];
extern asn_per_constraints_t asn_PER_type_RestrictionClassListEU_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RestrictionClassAssignmentEU.h"

#endif	/* _RestrictionClassListEU_H_ */
#include "asn_internal.h"
