/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RoadSegmentReferenceIDEU_H_
#define	_RoadSegmentReferenceIDEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RoadRegulatorIDEU.h"
#include "RoadSegmentIDEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RoadSegmentReferenceIDEU */
typedef struct RoadSegmentReferenceIDEU {
	RoadRegulatorIDEU_t	*region	/* OPTIONAL */;
	RoadSegmentIDEU_t	 id;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadSegmentReferenceIDEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadSegmentReferenceIDEU;
extern asn_SEQUENCE_specifics_t asn_SPC_RoadSegmentReferenceIDEU_specs_1;
extern asn_TYPE_member_t asn_MBR_RoadSegmentReferenceIDEU_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RoadSegmentReferenceIDEU_H_ */
#include "asn_internal.h"
