/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RTCMheaderEU_H_
#define	_RTCMheaderEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GNSSstatusEU.h"
#include "AntennaOffsetSetEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RTCMheaderEU */
typedef struct RTCMheaderEU {
	GNSSstatusEU_t	 status;
	AntennaOffsetSetEU_t	 offsetSet;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RTCMheaderEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RTCMheaderEU;
extern asn_SEQUENCE_specifics_t asn_SPC_RTCMheaderEU_specs_1;
extern asn_TYPE_member_t asn_MBR_RTCMheaderEU_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RTCMheaderEU_H_ */
#include "asn_internal.h"
