/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SignalStatusPackageEU_H_
#define	_SignalStatusPackageEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IntersectionAccessPointEU.h"
#include "MinuteOfTheYearEU.h"
#include "DSecondEU.h"
#include "PrioritizationResponseStatusEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SignalRequesterInfoEU;
struct IntersectionAccessPointEU;
struct RegionalExtensionEU;

/* SignalStatusPackageEU */
typedef struct SignalStatusPackageEU {
	struct SignalRequesterInfoEU	*requester	/* OPTIONAL */;
	IntersectionAccessPointEU_t	 inboundOn;
	struct IntersectionAccessPointEU	*outboundOn	/* OPTIONAL */;
	MinuteOfTheYearEU_t	*minute	/* OPTIONAL */;
	DSecondEU_t	*second	/* OPTIONAL */;
	DSecondEU_t	*duration	/* OPTIONAL */;
	PrioritizationResponseStatusEU_t	 status;
	struct SignalStatusPackageEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalStatusPackageEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalStatusPackageEU;
extern asn_SEQUENCE_specifics_t asn_SPC_SignalStatusPackageEU_specs_1;
extern asn_TYPE_member_t asn_MBR_SignalStatusPackageEU_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SignalRequesterInfoEU.h"
#include "IntersectionAccessPointEU.h"
#include "RegionalExtensionEU.h"

#endif	/* _SignalStatusPackageEU_H_ */
#include "asn_internal.h"
