/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SignalRequestMessageEU_H_
#define	_SignalRequestMessageEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MinuteOfTheYearEU.h"
#include "DSecondEU.h"
#include "MsgCountEU.h"
#include "RequestorDescriptionEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SignalRequestListEU;
struct RegionalExtensionEU;

/* SignalRequestMessageEU */
typedef struct SignalRequestMessageEU {
	MinuteOfTheYearEU_t	*timeStamp	/* OPTIONAL */;
	DSecondEU_t	 second;
	MsgCountEU_t	*sequenceNumber	/* OPTIONAL */;
	struct SignalRequestListEU	*requests	/* OPTIONAL */;
	RequestorDescriptionEU_t	 requestor;
	struct SignalRequestMessageEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalRequestMessageEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalRequestMessageEU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SignalRequestListEU.h"
#include "RegionalExtensionEU.h"

#endif	/* _SignalRequestMessageEU_H_ */
#include "asn_internal.h"
