/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SignalRequestEU_H_
#define	_SignalRequestEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IntersectionReferenceIDEU.h"
#include "RequestIDEU.h"
#include "PriorityRequestTypeEU.h"
#include "IntersectionAccessPointEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IntersectionAccessPointEU;
struct RegionalExtensionEU;

/* SignalRequestEU */
typedef struct SignalRequestEU {
	IntersectionReferenceIDEU_t	 id;
	RequestIDEU_t	 requestID;
	PriorityRequestTypeEU_t	 requestType;
	IntersectionAccessPointEU_t	 inBoundLane;
	struct IntersectionAccessPointEU	*outBoundLane	/* OPTIONAL */;
	struct SignalRequestEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalRequestEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalRequestEU;
extern asn_SEQUENCE_specifics_t asn_SPC_SignalRequestEU_specs_1;
extern asn_TYPE_member_t asn_MBR_SignalRequestEU_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IntersectionAccessPointEU.h"
#include "RegionalExtensionEU.h"

#endif	/* _SignalRequestEU_H_ */
#include "asn_internal.h"
