/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SignalHeadLocationEU_H_
#define	_SignalHeadLocationEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NodeOffsetPointXYEU.h"
#include "DeltaAltitude.h"
#include "SignalGroupIDEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SignalHeadLocationEU */
typedef struct SignalHeadLocationEU {
	NodeOffsetPointXYEU_t	 nodeXY;
	DeltaAltitude_t	 nodeZ;
	SignalGroupIDEU_t	 signalGroupID;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalHeadLocationEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalHeadLocationEU;
extern asn_SEQUENCE_specifics_t asn_SPC_SignalHeadLocationEU_specs_1;
extern asn_TYPE_member_t asn_MBR_SignalHeadLocationEU_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SignalHeadLocationEU_H_ */
#include "asn_internal.h"
