/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SignalGroupIDEU_H_
#define	_SignalGroupIDEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SignalGroupIDEU */
typedef long	 SignalGroupIDEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SignalGroupIDEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SignalGroupIDEU;
asn_struct_free_f SignalGroupIDEU_free;
asn_struct_print_f SignalGroupIDEU_print;
asn_constr_check_f SignalGroupIDEU_constraint;
ber_type_decoder_f SignalGroupIDEU_decode_ber;
der_type_encoder_f SignalGroupIDEU_encode_der;
xer_type_decoder_f SignalGroupIDEU_decode_xer;
xer_type_encoder_f SignalGroupIDEU_encode_xer;
oer_type_decoder_f SignalGroupIDEU_decode_oer;
oer_type_encoder_f SignalGroupIDEU_encode_oer;
per_type_decoder_f SignalGroupIDEU_decode_uper;
per_type_encoder_f SignalGroupIDEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SignalGroupIDEU_H_ */
#include "asn_internal.h"
