/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SPATEU_H_
#define	_SPATEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MinuteOfTheYearEU.h"
#include "DescriptiveNameEU.h"
#include "IntersectionStateListEU.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RegionalExtensionEU;

/* SPATEU */
typedef struct SPATEU {
	MinuteOfTheYearEU_t	*timeStamp	/* OPTIONAL */;
	DescriptiveNameEU_t	*name	/* OPTIONAL */;
	IntersectionStateListEU_t	 intersections;
	struct SPATEU__regional {
		A_SEQUENCE_OF(struct RegionalExtensionEU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SPATEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SPATEU;
extern asn_SEQUENCE_specifics_t asn_SPC_SPATEU_specs_1;
extern asn_TYPE_member_t asn_MBR_SPATEU_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RegionalExtensionEU.h"

#endif	/* _SPATEU_H_ */
#include "asn_internal.h"
