/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ThrottleConfidenceEU_H_
#define	_ThrottleConfidenceEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ThrottleConfidenceEU {
	ThrottleConfidenceEU_unavailable	= 0,
	ThrottleConfidenceEU_prec10percent	= 1,
	ThrottleConfidenceEU_prec1percent	= 2,
	ThrottleConfidenceEU_prec0_5percent	= 3
} e_ThrottleConfidenceEU;

/* ThrottleConfidenceEU */
typedef long	 ThrottleConfidenceEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ThrottleConfidenceEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ThrottleConfidenceEU;
extern const asn_INTEGER_specifics_t asn_SPC_ThrottleConfidenceEU_specs_1;
asn_struct_free_f ThrottleConfidenceEU_free;
asn_struct_print_f ThrottleConfidenceEU_print;
asn_constr_check_f ThrottleConfidenceEU_constraint;
ber_type_decoder_f ThrottleConfidenceEU_decode_ber;
der_type_encoder_f ThrottleConfidenceEU_encode_der;
xer_type_decoder_f ThrottleConfidenceEU_decode_xer;
xer_type_encoder_f ThrottleConfidenceEU_encode_xer;
oer_type_decoder_f ThrottleConfidenceEU_decode_oer;
oer_type_encoder_f ThrottleConfidenceEU_encode_oer;
per_type_decoder_f ThrottleConfidenceEU_decode_uper;
per_type_encoder_f ThrottleConfidenceEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ThrottleConfidenceEU_H_ */
#include "asn_internal.h"
