/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_TimeChangeDetailsEU_H_
#define	_TimeChangeDetailsEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TimeMarkEU.h"
#include "TimeIntervalConfidenceEU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TimeChangeDetailsEU */
typedef struct TimeChangeDetailsEU {
	TimeMarkEU_t	*startTime	/* OPTIONAL */;
	TimeMarkEU_t	 minEndTime;
	TimeMarkEU_t	*maxEndTime	/* OPTIONAL */;
	TimeMarkEU_t	*likelyTime	/* OPTIONAL */;
	TimeIntervalConfidenceEU_t	*confidence	/* OPTIONAL */;
	TimeMarkEU_t	*nextTime	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TimeChangeDetailsEU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeChangeDetailsEU;
extern asn_SEQUENCE_specifics_t asn_SPC_TimeChangeDetailsEU_specs_1;
extern asn_TYPE_member_t asn_MBR_TimeChangeDetailsEU_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _TimeChangeDetailsEU_H_ */
#include "asn_internal.h"
