/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../../cpm/F/kell/asd/with_riebl/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_TimeConfidenceEU_H_
#define	_TimeConfidenceEU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TimeConfidenceEU {
	TimeConfidenceEU_unavailable	= 0,
	TimeConfidenceEU_time_100_000	= 1,
	TimeConfidenceEU_time_050_000	= 2,
	TimeConfidenceEU_time_020_000	= 3,
	TimeConfidenceEU_time_010_000	= 4,
	TimeConfidenceEU_time_002_000	= 5,
	TimeConfidenceEU_time_001_000	= 6,
	TimeConfidenceEU_time_000_500	= 7,
	TimeConfidenceEU_time_000_200	= 8,
	TimeConfidenceEU_time_000_100	= 9,
	TimeConfidenceEU_time_000_050	= 10,
	TimeConfidenceEU_time_000_020	= 11,
	TimeConfidenceEU_time_000_010	= 12,
	TimeConfidenceEU_time_000_005	= 13,
	TimeConfidenceEU_time_000_002	= 14,
	TimeConfidenceEU_time_000_001	= 15,
	TimeConfidenceEU_time_000_000_5	= 16,
	TimeConfidenceEU_time_000_000_2	= 17,
	TimeConfidenceEU_time_000_000_1	= 18,
	TimeConfidenceEU_time_000_000_05	= 19,
	TimeConfidenceEU_time_000_000_02	= 20,
	TimeConfidenceEU_time_000_000_01	= 21,
	TimeConfidenceEU_time_000_000_005	= 22,
	TimeConfidenceEU_time_000_000_002	= 23,
	TimeConfidenceEU_time_000_000_001	= 24,
	TimeConfidenceEU_time_000_000_000_5	= 25,
	TimeConfidenceEU_time_000_000_000_2	= 26,
	TimeConfidenceEU_time_000_000_000_1	= 27,
	TimeConfidenceEU_time_000_000_000_05	= 28,
	TimeConfidenceEU_time_000_000_000_02	= 29,
	TimeConfidenceEU_time_000_000_000_01	= 30,
	TimeConfidenceEU_time_000_000_000_005	= 31,
	TimeConfidenceEU_time_000_000_000_002	= 32,
	TimeConfidenceEU_time_000_000_000_001	= 33,
	TimeConfidenceEU_time_000_000_000_000_5	= 34,
	TimeConfidenceEU_time_000_000_000_000_2	= 35,
	TimeConfidenceEU_time_000_000_000_000_1	= 36,
	TimeConfidenceEU_time_000_000_000_000_05	= 37,
	TimeConfidenceEU_time_000_000_000_000_02	= 38,
	TimeConfidenceEU_time_000_000_000_000_01	= 39
} e_TimeConfidenceEU;

/* TimeConfidenceEU */
typedef long	 TimeConfidenceEU_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TimeConfidenceEU_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TimeConfidenceEU;
extern const asn_INTEGER_specifics_t asn_SPC_TimeConfidenceEU_specs_1;
asn_struct_free_f TimeConfidenceEU_free;
asn_struct_print_f TimeConfidenceEU_print;
asn_constr_check_f TimeConfidenceEU_constraint;
ber_type_decoder_f TimeConfidenceEU_decode_ber;
der_type_encoder_f TimeConfidenceEU_encode_der;
xer_type_decoder_f TimeConfidenceEU_decode_xer;
xer_type_encoder_f TimeConfidenceEU_encode_xer;
oer_type_decoder_f TimeConfidenceEU_decode_oer;
oer_type_encoder_f TimeConfidenceEU_encode_oer;
per_type_decoder_f TimeConfidenceEU_decode_uper;
per_type_encoder_f TimeConfidenceEU_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeConfidenceEU_H_ */
#include "asn_internal.h"
