/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions-NEW"
 * 	found in "../../cpm/F/kell/asd/with_riebl/CPM_NEW.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_VehicleSubclass_H_
#define	_VehicleSubclass_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "ClassConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleSubclass__type {
	VehicleSubclass__type_unknown	= 0,
	VehicleSubclass__type_moped	= 1,
	VehicleSubclass__type_motorcycle	= 2,
	VehicleSubclass__type_passengerCar	= 3,
	VehicleSubclass__type_bus	= 4,
	VehicleSubclass__type_lightTruck	= 5,
	VehicleSubclass__type_heavyTruck	= 6,
	VehicleSubclass__type_trailer	= 7,
	VehicleSubclass__type_specialVehicles	= 8,
	VehicleSubclass__type_tram	= 9,
	VehicleSubclass__type_emergencyVehicle	= 10,
	VehicleSubclass__type_agricultural	= 11
} e_VehicleSubclass__type;

/* VehicleSubclass */
typedef struct VehicleSubclass {
	long	*type	/* OPTIONAL */;
	ClassConfidence_t	*confidence	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSubclass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSubclass;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleSubclass_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleSubclass_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSubclass_H_ */
#include "asn_internal.h"
