/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions-NEW"
 * 	found in "../../cpm/F/kell/asd/with_riebl/CPM_NEW.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "VruSubclass.h"

static int
memb_type_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_type_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_type_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_VruSubclass_1[] = {
	{ ATF_POINTER, 2, offsetof(struct VruSubclass, type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_type_constr_2, &asn_PER_memb_type_constr_2,  memb_type_constraint_1 },
		0, 0, /* No default value */
		"type"
		},
	{ ATF_POINTER, 1, offsetof(struct VruSubclass, confidence),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ClassConfidence,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"confidence"
		},
};
static const int asn_MAP_VruSubclass_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_VruSubclass_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_VruSubclass_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* confidence */
};
asn_SEQUENCE_specifics_t asn_SPC_VruSubclass_specs_1 = {
	sizeof(struct VruSubclass),
	offsetof(struct VruSubclass, _asn_ctx),
	asn_MAP_VruSubclass_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_VruSubclass_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_VruSubclass = {
	"VruSubclass",
	"VruSubclass",
	&asn_OP_SEQUENCE,
	asn_DEF_VruSubclass_tags_1,
	sizeof(asn_DEF_VruSubclass_tags_1)
		/sizeof(asn_DEF_VruSubclass_tags_1[0]), /* 1 */
	asn_DEF_VruSubclass_tags_1,	/* Same as above */
	sizeof(asn_DEF_VruSubclass_tags_1)
		/sizeof(asn_DEF_VruSubclass_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_VruSubclass_1,
	2,	/* Elements count */
	&asn_SPC_VruSubclass_specs_1	/* Additional specs */
};

